### PR TITLE
some ECDH functions we don't use that are no longer present in 1.1.0

### PR DESCRIPTION
**Pull request by reaperhulk**
pyOpenSSL does not use these.

### CODE REVIEW

**Comment by lvh** [comment]
I'm guessing pyOpenSSL is the only consumer we really care about? This obviously looks fine to me; my only concern is that something somewhere is calling this (but it seems improbable).

**Comment by alex** [comment]
It's the only external bindings consumer that I'm aware of.

**Comment by reaperhulk** [comment]
The only other people I can think of who might be using bindings separately would be @lukasa in his various pursuits or @glyph within Twisted. That said, I'm pretty sure that neither of them are using this :)

**Comment by lvh** [comment]
Correct; it does not. this looks good to me; thanks @reaperhulk! Can I just merge this or would you prefer me to wait for @Lukasa?

**Comment by alex** [comment]
Once tests pass this is fine to merge

**Comment by Lukasa** [comment]
I don't use these. =)

**Comment by alex** [comment]
Not sure what's going on with codecov, but it's clearly full coverage so I'm going to merge.

**Pull request merged**
