### PR TITLE
Require a newer setuptools.

### PR DESCRIPTION
**Pull request by alex**
This lets a long confusing comment.

@dstufft: PTAL :-)

### CODE REVIEW

**Comment by reaperhulk** [comment]
setuptools 11.3 was released Jan 2015 and the maintenance burden for us supporting the older versions is essentially non-existent. People who package us for distributions (for example, CentOS 7 or Ubuntu 14.04) will just end up patching this code back in downstream if their setuptools isn't new enough anyway.

If there's a legitimate need for a newer version then I'm happy to up the dependency, but as is this doesn't seem compelling.

**Comment by alex** [comment]
Are CentOS7 or Ubuntu 14.04 packaging newer versions of us?

**Comment by dstufft** [comment]
On non Debuntu systems you'll end up fighting with the package manager about what the contents of ``/usr/lib/pythonX.Y/site-packages/setuptools/*`` is since both pip and their package manager will expect to be able to control it. Not in an of itself a big deal, but something to consider.

**Comment by dstufft** [comment]
Otherwise though, this should work fine.

**Comment by alex** [comment]
FWIW, the impetus for this was: we selected the 1.0 minimum somewhat at random, I decided to read the changelog and see if there was something better. The two I came up with were:

* 1.3: Fixes a TLS verification bug
* 11.3: Let's us delete some code and comments

So yeah, is this likely to break anything for people?

**Comment by dstufft** [comment]
I can't think of anything it'd break that mentioning setuptools at all in ``install_requires`` wouldn't (due to the "upgrade everything" nature of ``pip install -U setuptools``). It just might mean that ``pip install cryptography`` (without the ``-U``) might end up doing an upgrade of setuptools as well, instead of that only happening if they use ``-U``.

**Comment by alex** [comment]
And does the possibility of the packaging issue @reaperhulk mentioned concern you?

**Comment by dstufft** [comment]
Not majorly. I think it'd only be a concern for backports style repositories of those distros since anyone pulling in a brand new version of cryptography at this point should be able to pull in a new version of setuptools too I think. Like, I don't think that Debian is going to add a new version of cryprography to Jesse except perhaps via jesse-backports. @mithrandi might have a different opinion.

**Comment by mithrandi** [comment]
The odds of seeing a wholesale cryptography stable update (ie. in jessie, not jessie-backports) are pretty low unless there's a change in stable update policies.

And in jessie-backports, we can always backport a newer setuptools if it's necessary, so (speaking with my Debian Developer and python-cryptography maintainer hat on) I don't expect this to cause any problems.

**Comment by reaperhulk** [comment]
Consider me outvoted I suppose!

**Comment by alex** [comment]
Thanks @mithrandi !

**Pull request merged**
