### PR TITLE
Add flag to toggle key length check for HOTP and TOTP.

### PR DESCRIPTION
**Pull request by Ayrx**
Potential fix for #2915. 

Out of all the API changes suggested, I feel like this one is the cleanest. It does go against project convention but it's the only API change that is backwards compatible. I'm not a fan of all the other suggestions that adds way too much complexity for my tastes.

### CODE REVIEW

**Comment by Ayrx** [comment]
jenkins retest this please

**Comment by tonyseek** [comment]
It looks well. 👍

**Comment by reaperhulk** [comment]
Hmm, we discussed perhaps just making the key length check a function that could be overridden if needed in #2915. I'm not sure I'm a fan of that approach (as it'd be a private method and while it could be monkeypatched there's no guarantee that we wouldn't change the implementation in the future), but it seems worth making sure everybody agrees we don't want to do it that way.

**Comment by Ayrx** [comment]
@reaperhulk Yeah, I saw that approach. I'm definitely not a fan of anything that encourages monkeypatching since imo that's just asking for trouble in the future. 

Regardless of which way we decide to go with eventually, it's good to have a concrete PR to discuss against.

**Comment by Ayrx** [comment]
@alex, @reaperhulk: Just a poke on this. Any feedback so far? :)

**Comment by reaperhulk** [comment]
I think I've made my peace with this approach. Needs a versionadded on the param though.

**Comment by reaperhulk** [comment]
This is blocked on #3040

**Comment by Ayrx** [comment]
jenkins retest this please

**Comment by Ayrx** [comment]
All clear on the CI front now.

**Pull request merged**
