### PR TITLE
Dump pkcs12

### PR DESCRIPTION
**Pull request by Kuro66**
Added methods to the PKCS12KeyandCertificates and to the PKCS12Certificate classes to allow easier dump of certificate and key by converting them into bytes.

### CODE REVIEW

**Comment by alex** [comment]
This is not the approach we take to API design in cryptography, we prefer composability.

Because there is nothing in these APIs that is PKCS12 specific, its more appropriate for the methods to be on the key and certificate classes, as they already are.

**Comment by Kuro66** [comment]
Hello Alex,
I just thought it would make it easier. I came here after using pyOpenSSL and receiving a deprecation warning. pyOpenSSL had those sorts of features and I must admit I was a bit lost when I arrived here and had to untangle how it all worked in order to find out what to call on what. So I thought it could help people in the same situation as I was in.

**Comment by alex** [comment]
pyOpenSSL is deprecated for exactly these reasons :-) The lack of
composability/orthogonality in its design makes it painful to
maintain.

On Fri, Feb 10, 2023 at 8:06 AM Kuro ***@***.***> wrote:
>
> Hello Alex,
> I just thought it would make it easier. I came here after using pyOpenSSL and receiving a deprecation warning. pyOpenSSL had those sorts of features and I must admit I was a bit lost when I arrived here and had to untangle how it all worked in order to find out what to call on what. So I thought it could help people in the same situation as I was in.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by Kuro66** [comment]
Okay, I didn't know that.
Not reproducing the same mistake would indeed be a good idea. :)

**Comment by alex** [comment]
Thanks for your interest in contributing.

**Pull request closed without merging**
