### PR TITLE
Move cryptography package one level down.

### LINKED ISSUE #1473: Better handle multiple packages
Right now the cryptography repository has two packages inside of it. It has the "primary" package of cryptography which is located at `.`, and then a "secondary" package of cryptography_vectors. In #1456a third one is added which is cryptography_scrypt.

This organization is confusing, we have packages inside of packages. I think we should either decide if we want to hold multiple packages in one repository and if we do we should reorganize the repository to not do this nesting thing.

To be exact the proposal is to change the directory structure to:

```
.
├── cryptography
│   ├── setup.py
│   └── src
│       └── cryptography
├── cryptography_scrypt
│   ├── cryptography_scrypt
│   └── setup.py
└── cryptography_vectors
    ├── cryptography_vectors
    └── setup.py
```

If we're going to hold everything in a single repository. If we're not going to hold everything in a single repository then instead of having a single repository at `.` each direct descendent (cryptography, cryptography_scrypt, cryptography_vectors) would have it's own repository.

Personally I think it sort of makes sense sense to have cryptography and cryptography_vectors in the same repository (primarily because the split really only exists because of file size), but I do not think it makes sense to include other random backends in the same repository. Overall I think putting multiple things into the same repository isn't a very good way to organize things. Pip has some newish support for layouts like this, but I don't believe anything else does.

My vote is to stick to one repository per package.

### PR DESCRIPTION
**Pull request by Ayrx**
Moves the cryptography package one level down.

Fixes #1473.  Ref #1522.

### CODE REVIEW

**Comment by public** [comment]
Windows supports symlinks as long as you aren't using FAT32 right?

**Comment by Ayrx** [comment]
@public I have done some research and it seems like msysgit (what looks like the most popular git thing used in Windows-land?) [doesn't seem to support symlinks][0]. Looks like that's a no-go.

[0]: https://www.quora.com/How-does-git-handle-symbolic-links-on-Windows

**Comment by reaperhulk** [comment]
We need a final answer on README/AUTHORS before we can merge this.

**Comment by Ayrx** [comment]
@reaperhulk As far as the README goes each package will have a package-specific README once I factor out the primitives and interfaces into another package. I think there's little harm just duplicating the file at the moment.

I'll need an answer on what to do with the AUTHORS files though. :)

So I see three options.
1. Moving it back into the root and leaving it out of the sdist.
2. Autogenerate it. (Not sure how to do this though, I'll need someone to point me at an example...)
3. Some packaging voodoo I don't know about so it can stay in the root and still go into the sdist.

**Comment by reaperhulk** [comment]
The release script could copy it from root probably?

**Pull request closed without merging**
