### PR TITLE
Start splitting out interfaces with ciphers

### PR DESCRIPTION
**Pull request by greghaynes**
The interfaces module is getting unwieldy so starting to split this out.
Beginning by creating a ciphers module.

This starts implementing issue #1495

### CODE REVIEW

**Comment by Ayrx** [comment]
:+1: This looks merge-ready to me.

**Comment by reaperhulk** [comment]
Do we want to split these into submodules or move the interfaces to live near the primitives they're associated with? (For example, cipher interfaces could live somewhere in `cryptography.hazmat.primitives.ciphers`)

**Comment by alex** [comment]
I think long term we want to move them to by near with the primtivies
they're for, however, we can move them to `interfaces/ciphers.py` and
re-export them in `__init__.py` without leading to any backwards
incompatibility or churn. (That is to say, we don't deprecate the old
locations).

**Comment by reaperhulk** [comment]
I'm okay with that. Thanks for the contribution @greghaynes. I'll merge now. Feel free to send a PR adding your name to the `AUTHORS.rst` file.

**Pull request merged**
