### PR TITLE
Make Fernet.generate_key a staticmethod

### PR DESCRIPTION
**Pull request by bsolomon1124**
Change from `@classmethod` to `@staticmethod`.

Method contains no reference to the class (or class instance), so better fits the bill of a staticmethod, which also makes the docs clearer.

### CODE REVIEW

**Comment by alex** [comment]
Is there a functional reason to make this change?

**Comment by bsolomon1124** [comment]
Frankly, no--it's grammatical, for lack of a better word.  Denoting it a staticmethod makes it more clear what it's designed to do and what it returns.  A classmethod (because it takes the class as its first argument implicitly) typically has a _reason_ to use that object within the method's scope, which is not the case here.

**Comment by alex** [comment]
Ok. I think it's preferable to leave this as is -- it gives us the flexibility to do things like invoke other class methods or use class constants (and frankly factoring out key length into a constant wouldn't be the worst idea).

Thanks for the PR though!

**Comment by bsolomon1124** [comment]
Okay, fair - your call!

**Pull request closed without merging**
