### PR TITLE
Try codecov again

### PR DESCRIPTION
**Pull request by reaperhulk**
Let's see if they've fixed their stuff.

### CODE REVIEW

**Comment by alex** [comment]
I think we'r eusing coveralls wrong, from the log: https://travis-ci.org/pyca/cryptography/jobs/61822446#L1604

**Comment by reaperhulk** [comment]
pypy and pypy3 don't generate coverage :)

That said, looks like it's still not going to work. From the py34 job:

```
$ source ~/.venv/bin/activate && codecov --env TRAVIS_OS_NAME TOX_ENV OPENSSL CC
Uploaded: False
Report URL: n/a
Upload Version: codecov-v1.1.7
Message: Pull request coverage is coming soon. Thank you for your patience!
```

**Comment by alex** [comment]
Oh, uh, right. My bad.

On Fri, May 8, 2015 at 5:53 PM, Paul Kehrer <notifications@github.com>
wrote:

> pypy and pypy3 don't generate coverage :)
>
> That said, looks like it's still not going to work. From the py34 job:
>
> $ source ~/.venv/bin/activate && codecov --env TRAVIS_OS_NAME TOX_ENV OPENSSL CC
> Uploaded: False
> Report URL: n/a
> Upload Version: codecov-v1.1.7
> Message: Pull request coverage is coming soon. Thank you for your patience!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1912#issuecomment-100377807>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by public** [comment]
We use Codecov at work and it generates per-PR coverage for us?

**Comment by reaperhulk** [comment]
@public yeah no idea what's going on. I just ran the builds again and got the same message (https://travis-ci.org/pyca/cryptography/jobs/61822423 look at the end)

**Comment by public** [comment]
Well this is unfortunate. 
screenshot from 2015-05-16 16 18 39

**Comment by alex** [comment]
hahahahahahaha, <3 can we report the bug to them?

On Sat, May 16, 2015 at 11:19 AM, Alex Stapleton <notifications@github.com>
wrote:

> Well this is unfortunate.
> [image: screenshot from 2015-05-16 16 18 39]
> <https://cloud.githubusercontent.com/assets/83000/7666719/46389d42-fbe7-11e4-8df4-ae35ffb63be1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1912#issuecomment-102637264>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by public** [comment]
I think it worked that time. Will re run the whole Travis job.

**Comment by alex** [comment]
A+

On Sat, May 16, 2015 at 11:25 AM, Alex Stapleton <notifications@github.com>
wrote:

> I think it worked that time. Will re run the whole Travis job.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1912#issuecomment-102638043>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by stevepeak** [comment]
Hey Friends, Steve from Codecov here. I'll be fixing that bug right now. Thanks for letting me know. :)

**Comment by public** [comment]
Thanks :)

**Comment by alex** [comment]
You rock!

On Sat, May 16, 2015 at 11:26 AM, Steve Peak <notifications@github.com>
wrote:

> Hey Friends, Steve from Codecov here. I'll be fixing that bug right now.
> Thanks for letting me know. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1912#issuecomment-102638575>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by stevepeak** [comment]
And deployed! Cheers :+1:

**Comment by public** [comment]
Yep. Set it to 100%.

**Comment by stevepeak** [comment]
Let me know if there is anything I can help out with. There has been many new features and enhancements recently. I'm very active on development, so your feedback is greatly appreciated.

**Comment by public** [comment]
@stevepeak Well it uploaded stuff. Doesn't seem to have posted any comments or done the status API thing though. I'm not entirely sure it's picking up all the environment variables properly. Most of them seem to be blank, but maybe @reaperhulk configured it incorrectly...

**Comment by reaperhulk** [comment]
Never underestimate my capacity to make mistakes. No idea if this is wrong though :)

**Comment by stevepeak** [comment]
Hey, 

So the environment variables code is [here](https://github.com/codecov/codecov-python/blob/09dfd026ef0b52b307d2d89e930285c90070df41/codecov/__init__.py#L110-L111). The report does indeed show a value of `CC=""` via curl:

```shell
curl -X GET -H 'Accept: application/json' https://codecov.io/github/pyca/cryptography?ref=29a08e8463847912c2a68ee0ac0fb42d8e3e9d65
```

As for the comment: I'm digging through the logs and I'll get back to you on what I find (afk for a little).

Thanks!

**Comment by stevepeak** [comment]
Making progress https://codecov.io/github/pyca/cryptography/src/cryptography?ref=d47946f3d3e358b706e996d0b951d496ffc2461f Thanks

**Comment by reaperhulk** [comment]
Awesome @stevepeak definitely getting better. I'm still seeing some weirdness on merging for branch coverage though. For example, the merged coverage claims we've only taken one branch here despite both of the branches showing the lines are covered: https://codecov.io/github/pyca/cryptography/src/cryptography/utils.py?ref=d47946f3d3e358b706e996d0b951d496ffc2461f#l-52

Digging into the builds:
Else branch: https://codecov.io/github/pyca/cryptography/src/cryptography/utils.py?ref=d47946f3d3e358b706e996d0b951d496ffc2461f&build=6073.1#l-52
primary branch: https://codecov.io/github/pyca/cryptography/src/cryptography/utils.py?ref=d47946f3d3e358b706e996d0b951d496ffc2461f&build=6073.2#l-52

As a side note, it'd be super awesome if the TOXENV var (or all the env vars) could somehow appear in the build dropdown so I can know which builds had which env vars.

Thanks again for working with us on this!

**Comment by stevepeak** [comment]
@reaperhulk I'm trying my best to get this perfect for your team! Thank you so much for being patient and working with me :)

The branch coverage is a little tricky. I believe the best (maybe only way) to fix this is via this PR: https://bitbucket.org/ned/coveragepy/pull-request/53/store-missed-branches-data-in-xml-report/diff

I can append the environment variables to the build dropdown. That is one option. It may however be to large in the UI. What do you think about one of these options (**a**) tooltip when hovering, or (**b**) a different page to view all the details for a build. (I think **b**) Thoughts?

**Comment by reaperhulk** [comment]
@stevepeak B would be a fine solution :)

**Comment by alex** [comment]
This has been supceded by #2070

**Pull request closed without merging**
