### PR TITLE
correctly apply the Apache-2.0 License

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
According to the Apache 2.0 license you need to include the boilderplate, and you really need to include the copyright holders: https://github.com/pyca/cryptography/pull/3097/files#diff-0a77fdccb61e3d61ba13949e89b5bf80R1

**Comment by sigmavirus24** [comment]
This is stemming from sigmavirus24/uritemplate#25. I'm fairly confident this can be closed.

**Comment by graingert** [comment]
actually it looks like https://github.com/pyca/cryptography/issues/1209 "Figure out what to do with copyright headers in every file" was never done

**Comment by sigmavirus24** [comment]
1. This change would have no effect on that.
2. In sigmavirus24/uritemplate#25 I linked you an example of how copyright is notified in *each* file in this project. Someone forgot to check a box on that issue. That is all.

**Comment by graingert** [comment]
sure, but I think there's still an issue here. I'm not sure what Van Lindberg was consulted on, but I'm like 60% sure he would not contradict the explicit wording of the Apache-2.0 license.

**Comment by reaperhulk** [comment]
When we consulted our lawyer it was explicitly to discuss relicensing to from Apache 2 to dual Apache 2 and BSD 3 clause. Within this discussion was a question about license headers, from which the current solution arose.

In this case it appears your concerns arise from a section after the end of terms and conditions and relates to one way (and notably not the *only* way) to make users of the software aware of the license it is provided under. That summary is just my opinion of this and I am definitively not a lawyer, but as we have consulted an IP lawyer about this very situation we're satisfied with our current approach.

**Pull request closed without merging**
