### PR TITLE
Attempt to use sccache

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
awaiting a resolution to https://github.com/mozilla/sccache/issues/1250

**Comment by reaperhulk** [comment]
Do we have a run that shows the ideal caching? In the last two successful runs it's still spending 30-60s compiling the rust despite nothing changing, but that may be just because the cache isn't hot? I'd like to understand best case here.

**Comment by alex** [comment]
Take a look at the post-cache output in the job. What you'll see is that for most of them, there's close to a 100% cache rate... for cacheable items. Unfortunately not every compilation is cacheable, see https://github.com/mozilla/sccache#rust

**Comment by reaperhulk** [comment]
I don't love that, but I guess we'll merge and see how this feels...

**Review by reaperhulk — APPROVED** [review]

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
