### PR TITLE
use setuptools.parse_version in _version_check

### PR DESCRIPTION
**Pull request by craigahobbs**
This eliminates the dependency on packaging.

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by alex** [comment]
@dstufft can you please tell us what to do here :-)

**Comment by alex** [comment]
@craigahobbs what's the motivation here? Modern `setuptools` depends on `packaging` so it's not like this adds a new dependency.

**Comment by dstufft** [comment]
I think that the only benefit to this is old setuptools and possibly future setuptools if we convince jaraco to re-bundle his deps. Whether that's worth it or not I dunno, but besides that the change looks fine on the surface.

**Comment by alex** [comment]
Oh. I just realized, a downside of this is `pkg_resources` is super slow to import.

**Comment by dstufft** [comment]
We already use ``pkg_resources`` to iterate the list of installed backends though right?

**Comment by alex** [comment]
We moved that import into the function, so it's only imported when you call `default_backends`.

**Comment by alex** [comment]
`_version_check` is called at module scope, so there's no equivilant solution.

**Comment by dstufft** [comment]
Ah right.

**Comment by craigahobbs** [comment]
Regarding motivation, it is solely to eliminate the dependency on packaging.  Not a huge deal.  We're using Python 3.6 and use the setuptools included with Python.  Interestingly, it seems to include packaging - it imports it like this "from pkg_resources.extern import packaging" - not that I'd recommend that.

**Comment by reaperhulk** [comment]
Yeah we moved to depend directly on `packaging` to avoid the import time side effects of `pkg_resources`. So we can't switch back without causing a regression. Sorry, but thanks for the contribution anyway! It's definitely non-obvious why we're doing it this way.

refs #3347 and #3190

**Pull request closed without merging**
