### PR TITLE
add docs on how to upgrade OpenSSL on OS X and windows builders

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
@reaperhulk sigh, any clue what's up with the coverage here?

**Comment by reaperhulk** [comment]
Same thing happened on the security hardening PR. Best guess is something changed in the Travis environment.

**Comment by alex** [comment]
Something that caused us to actually lose coverage?

On Tue, Sep 22, 2015 at 8:52 PM, Paul Kehrer <notifications@github.com>
wrote:

> Same thing happened on the security hardening PR. Best guess is something
> changed in the Travis environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2361#issuecomment-142464334>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
If the OpenSSL version changed that would do it. I took a quick look and nothing jumped out though. Looks like we're still on 1.0.1 for the linux docker images...

**Comment by alex** [comment]
@reaperhulk oh fuck, I bet it's the new version of coverage.py

**Comment by alex** [comment]
I'll write some tests for multibackend

**Comment by reaperhulk** [comment]
oooh, yeah 4.0 is out. Our underlying tooling has been undergoing dramatic upgrades of late...

**Comment by alex** [comment]
plz rebase

**Pull request merged**
