### PR TITLE
Fixed #2121 -- added __eq__ and __ne__ to CSRs

### LINKED ISSUE #2121: x509.CSR: implement equality
Since `x509.Certificate.__eq__` is implemented, I would expect a similar behavior for `x509.CertificateSigningRequest.__eq__`. Thanks!

```
(venv)jakub@iks:~/dev/letsencrypt/letsencrypt/acme/jose/testdata$ pip show cryptography
---
Name: cryptography
Version: 0.9.2
Location: /home/jakub/dev/letsencrypt/letsencrypt/venv/lib/python2.7/site-packages
Requires: idna, pyasn1, six, setuptools, enum34, ipaddress, cffi
(venv)jakub@iks:~/dev/letsencrypt/letsencrypt/acme/jose/testdata$ cat t2.py
from cryptography import x509
from cryptography.hazmat.backends import default_backend

with open("cert.der") as cert_file:
    data = cert_file.read()
    cert1 = x509.load_der_x509_certificate(data, default_backend())
    cert2 = x509.load_der_x509_certificate(data, default_backend())

with open("csr.der") as req_file:
    data = req_file.read()
    req1 = x509.load_der_x509_csr(data, default_backend())
    req2 = x509.load_der_x509_csr(data, default_backend())

print repr(cert1)
print repr(req1)
print cert1 == cert2, req1 == req2
(venv)jakub@iks:~/dev/letsencrypt/letsencrypt/acme/jose/testdata$ python t2.py
<cryptography.hazmat.backends.openssl.x509._Certificate object at 0x7f44e221a550>
<cryptography.hazmat.backends.openssl.x509._CertificateSigningRequest object at 0x7f44e221a710>
True False
```

### PR DESCRIPTION
**Pull request by alex**
OpenSSL doesn't have X509_REQ_cmp, so I went with just comparing the DER bytes, is there a better way?

### CODE REVIEW

**Comment by reaperhulk** [comment]
The DER representation is canonical so that'll work fine. You could just compare fingerprints though (that's the hash of the DER bytes)

**Comment by alex** [comment]
@reaperhulk a) CSR doesn't have a fingerprint method, b) what would the advantage of comparing a has be? seems like it would just be slower

**Comment by reaperhulk** [comment]
Since there's no fingerprint method I'd say there's no advantage.

**Comment by kuba** [comment]
what about `__hash__`, similarly to #2124?

**Comment by alex** [comment]
When this lands I'll do a follow up PR, one at a time :-)

**Comment by alex** [comment]
(I filed it now #2127)

**Pull request merged**
