### PR TITLE
Run tests on centos8

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Ahhh, https://github.com/openssl/openssl/issues/8450 is almost certainly the issue. So these tests need to be skipped. Great.

**Comment by alex** [comment]
Err, maybe not, we don't enable FIPS mode yet...

@tiran can you think of any modifications that CentOS 8 does to OpenSSL that might cause it to have custom allocators not work?

**Comment by reaperhulk** [comment]
This is because our centos8 container contains `/etc/system-fips` so we're getting some FIPS-y nonsense. We could remove this file and it would work, although I'm curious whether @tiran or another RH dev can explain why this is (at least partially) enabling FIPS without showing FIPS_mode of 1 in OpenSSL itself.

**Comment by alex** [comment]
@reaperhulk should we kill the `/etc/fips` thing?

**Comment by reaperhulk** [comment]
Probably the right way forward for now. FIPS is a separate PR with several other issues to solve before we could re-add the file to this container.

**Pull request merged**
