### PR TITLE
Add a Versioning section to the API stability docs

### PR DESCRIPTION
**Pull request by dmtucker**
This patch aims to articulate the versioning/tagging scheme used by the project.

### CODE REVIEW

**Comment by dmtucker** [comment]
`sphinxcontrib-spelling` thinks "versioning" is not a word:
```
api-stability.rst:38: (Versioning) 
api-stability.rst:40: (versioning)
```
Should I go with "tagging" instead?

Also, I'm not sure why Travis thinks there are 4 misspellings. Local runs and the Jenkins run only indicates the 2 above. Is there a way to access the spelling checker messages there?

**Comment by alex** [comment]
`docs/spelling_wordlist.txt` -- you can add a word there

**Comment by reaperhulk** [comment]
CI is currently failing on this:

```
api-stability.rst:47:th:
api-stability.rst:47:th:
```

No idea.

**Comment by dmtucker** [comment]
Oh, it probably means the "th" from 19th/20th on line 48.

**Pull request merged**
