### PR TITLE
20151230 no passphrase

### PR DESCRIPTION
**Pull request by nbastin**
Specialized exception for attempting key decryptions that don't need a passphrase.

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by reaperhulk** [comment]
Not sure what's going on with coverage here, @alex?

The exception needs to be documented in the docs (under both load_pem_private_key and load_der_private_key in serialization.rst)

**Comment by reaperhulk** [comment]
@nbastin are you still interested in working on this PR?

**Comment by nbastin** [comment]
Yeah, let me find some time - it's summer now so maybe I can get back to this.

**Comment by reaperhulk** [comment]
I'm going to go ahead and close this PR for now. If you decide to work a bit more on it feel free to resubmit!

**Pull request closed without merging**
