### PR TITLE
Build PDF version of docs

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Has someone asked for this?

**Comment by TheScriptGuy** [comment]
Hi! I requested this. 

I'm trying out some AI related things whereby I feed the AI a PDF document and ask it to help generate sample code or help understand more about the documentation.

**Comment by reaperhulk** [comment]
Good enough for me, thanks for speaking up!

**Review by reaperhulk — APPROVED** [review]

**Comment by TheScriptGuy** [comment]
How does the pdf enablement work? Is it only for newer versions of documentation (once approved for release) or will it be retroactively done for current and previous versions?

**Comment by reaperhulk** [comment]
It will auto generate on latest and any new tags going forward. Older releases will not have it.

**Comment by TheScriptGuy** [comment]
Legend! Thanks for your help and quick response!

**Pull request merged**
