### PR TITLE
Th3b0x tls method patch

### PR DESCRIPTION
**Pull request by th3b0x**
This PR addresses the **TLS_method** issues presented in Issue #5379

This patch will allow developers to use the newer TLS_method interface name, allowing them to write code that is compatible with future iterations of the OpenSSL library and its interfaces/conventions as they emerge, and will reduce false positives in static analysis tools which flag deprecated SSL/TLS modes.

Added mapping of TLS_Method to SSLv23_method (the opposite of what OpenSSL project did for backwards compatibility). The rationale is that since SSLv23_method gets mapped to TLS_method during compiler preprocessing, this will not break newer versions of the Cryptography package that user newer versions of OpenSSL (because SSLv23_method = TLS_method), while simultaneously providing the TLS_method interface via CFFI for all versions of the Cryptography package (including versions that __only__ have SSLv23_method) (in this case, TLS_method = SSLv23_method)

### CODE REVIEW

**Comment by reaperhulk** [comment]
(This isn't passing tests so it's not really reviewable yet)

**Comment by th3b0x** [comment]
> (This isn't passing tests so it's not really reviewable yet)

Hi @reaperhulk I've been inactive over the past month.  I recently had the opportunity to return to this item.  __I will tag you in a reply to this ticket when the patch is fixed.__

As an update on progress, I've had to make some minor changes to my build system.  I have a few notes regarding updates that should be made to the pyca-cryptography Development and Installation instructions as a consequence of this activity.  Is there a convention for updating the docs, or do documentation updates work exactly the same as everything else?  I ask because some projects have designated parties for approving documentation updates.

**Comment by reaperhulk** [comment]
Just submit a separate PR for any docs updates please. We use the same review and merge strategy for docs and code on this project.

**Comment by th3b0x** [comment]
@reaperhulk uh, not sure what's going on here, I think some changes I made for PEP8 compliance (I edited a version check conditional into multiple lines) seem to be breaking the **codecov** tests, and the **docs** are failing to build for no apparent reason (made no changes there).

Other than that, everything _appears_ to be passing.  Any thoughts?

**Comment by th3b0x** [comment]
Well, now that I've gone through this exercise, I now realize that I have far too much code from the Master branch for me to be bothered with Rebasing and Squashing, so I'm going to close this PR, put the _very simple_ patch in another branch, and submit a new PR with _just the relevant information_ included.  Lazy, sloppy, and confusing; I really should've seen this coming.

**Pull request closed without merging**
