### PR TITLE
Fix build with LibreSSL 2.7

### PR DESCRIPTION
**Pull request by Sp1l**
For readability of the block I duplicated the version stuff in `src/_cffi_src/openssl/cryptography.py`.
The rest are small changes for things that LibreSSL has not added from the 1.1.0 branch.

Tested with
  - OpenSSL 1.1.0h
  - LibreSSL 2.7.2
on 2.1.4 version

Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>

### CODE REVIEW

**Comment by alex** [comment]
Looks like there are some pep8 issues with line length, can you take a look at fixing those?

Thanks for working on this!

**Comment by Sp1l** [comment]
Yeah, noticed the line lenght issues that in the CI logs. Will update the pull-request.

**Comment by Sp1l** [comment]
Don't think I caused this 🎲 
```
Processing c:\jenkins\workspace\4210-64rvgrj46en7div@4\cryptography\vectors
Collecting coverage==4.3.4
  Could not find a version that satisfies the requirement coverage==4.3.4 (from versions: )
No matching distribution found for coverage==4.3.4

ERROR: could not install deps [coverage==4.3.4,
```

**Comment by alex** [comment]
No, you didn't. Grrr, it's a flake, I've restarted the build.

**Comment by alex** [comment]
https://github.com/pypa/pip/issues/5345 is an issue that I believe describes what happened here

**Comment by alex** [comment]
Ok, jenkins is green now.

**Comment by Sp1l** [comment]
Do check what I've done, please. I do a lot of C #ifdef-fing in a lot of projects but this Python cffi stuff is definitely not my expertise 😆

**Comment by mjb2010** [comment]
FWIW, I successfully tested these patches on FreeBSD 11-STABLE/armv6, like this:

# cd /usr/ports/security/py27-cryptography
# fetch https://patch-diff.githubusercontent.com/raw/pyca/cryptography/pull/4210.diff
# mkdir files && sed 's/^--- a/--- ./' 4210.diff > files/patch-4210
# make

There were no errors in the build. This was just patching against version 2.1.4.
HTH

**Comment by Sp1l** [comment]
Result of make test with patched 2.1.4 on FreeBSD 11.1-p9 with LibreSSL 2.7.3
[make-test.log](https://github.com/pyca/cryptography/files/1998411/make-test.log)

I was able to build master/fix-libressl27 branch without any 'implicit declaration' errors. `make test` failed as it wanted to install things in /usr/local as non-root.

**Comment by Vintodrimmer** [comment]
Good day,

Cryptography builds without errors with LibreSSL 2.7.3.

**Comment by simlu** [comment]
When is this being merged? Thanks!

**Comment by reaperhulk** [comment]
We won't be merging support until it works across all our supported versions of OpenSSL. This patch does not. #4234 extends this work but the approach used there is too complex to maintain going forward so the author is trying to come up with a simpler way to do it. So we have no timeline for merge because we don't have a mergeable patch at the moment, sorry.

I'm actually going to go ahead and close this PR since other PRs have taken up the work, but Bernard feel free to open a new PR if you want to!

**Pull request closed without merging**
