### PR TITLE
Disallow wildcards in DNSName for name constraints

### PR DESCRIPTION
**Pull request by gbansaghi**
As discussed in #8253, wildcards are unnecessary according to RFC 5280, and cause issues with at least Firefox.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Could you add a changelog entry noting this change? Thanks for the contribution!

**Comment by gbansaghi** [comment]
@reaperhulk I added the note, is there any way to verify that I got the links right before I push?

**Comment by alex** [comment]
You can build docs locally with tox -e docs

**Comment by reaperhulk** [comment]
You can also just push it and see if it builds appropriately in CI (we have a docs job where you can look at the built output).

**Review by reaperhulk — APPROVED** [review]

**Comment by gbansaghi** [comment]
The local docs build failed because of one misspelled word, but it didn't say where and persisted even after I rolled back my changes, so probably unrelated.

@reaperhulk I got a notification from github the second I hit push and was briefly but intensely confused.

**Comment by reaperhulk** [comment]
Thanks for the contribution @gbansaghi!

**Pull request merged**
