### PR TITLE
add extendedkeyusage extension

### PR DESCRIPTION
**Pull request by reaperhulk**
refs #1743

### CODE REVIEW

**Comment by alex** [comment]
waiiiiit, I'm so confused, what si the difference between KU and EKU?

**Comment by reaperhulk** [comment]
KU is a set of 9 flags that can be present to restrict a certificate's capabilities. EKU is a list of OIDs (with a few explicitly defined in the RFC, but no restriction technically on defining whatever you want for your own private PKI). Some EKUs complement KU flags (e.g. you want digitalSignature KU if you have a serverAuth, clientAuth, emailProtection, or codeSigning EKU) but the RFC states that EKU can be used in place of KU. In practice I am unsure how aggressively KUs are checked in the presence of an EKU. I'd be willing to bet that you can set your KU to not allow digital signature and no library will prohibit it if an EKU that needs it is present.

**Comment by alex** [comment]
Ugh. So there's really nothing better we can present than a list of OIDs?

On Tue, Mar 31, 2015 at 9:39 AM, Paul Kehrer <notifications@github.com>
wrote:

> KU is a set of 9 flags that can be present to restrict a certificate's
> capabilities. EKU is a list of OIDs (with a few explicitly defined in the
> RFC, but no restriction technically on defining whatever you want for your
> own private PKI). Some EKUs complement KU flags (e.g. you want
> digitalSignature KU if you have a serverAuth, clientAuth, emailProtection,
> or codeSigning EKU) but the RFC states that EKU can be used in place of KU.
> In practice I am unsure how aggressively KUs are checked in the presence of
> an EKU. I'd be willing to bet that you can set your KU to not allow digital
> signature and no library will prohibit it if an EKU that needs it is
> present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1808#issuecomment-88088643>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
We could also add support for properties that return a bool for the OIDs defined in the RFC. That'd let you do something like

```python
eku = cert.extensions.get_extension_for_oid(x509.OID_EXTENDED_KEY_USAGE)
if eku.server_auth:
    print("this certificate has the serverAuth EKU usage")
```

You'd still need it to be iterable to obtain OIDs that we don't have convenience properties for though.

**Comment by alex** [comment]
Are EKUs not in the RFC common?

On Tue, Mar 31, 2015 at 9:45 AM, Paul Kehrer <notifications@github.com>
wrote:

> We could also add support for properties that return a bool for the OIDs
> defined in the RFC. That'd let you do something like
>
> eku = cert.extensions.get_extension_for_oid(x509.OID_EXTENDED_KEY_USAGE)if eku.server_auth:
>     print("this certificate has the serverAuth EKU usage")
>
> You'd still need it to be iterable to obtain OIDs that we don't have
> convenience properties for though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1808#issuecomment-88090201>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
No, they're very unusual.

**Comment by alex** [comment]
I guess let's start with just the iteration, but when we land this file an
issue to discuss adding properties.

On Tue, Mar 31, 2015 at 9:47 AM, Paul Kehrer <notifications@github.com>
wrote:

> No, they're very unusual.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1808#issuecomment-88091399>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Pull request merged**
