### PR TITLE
Add loader for ECDH test vectors

### PR DESCRIPTION
**Pull request by simo5**
Also fix test vector files, they had a truncated line for the EE set in
both init and resp files.

Signed-off-by: Simo Sorce <simo@redhat.com>

### CODE REVIEW

**Comment by alex** [comment]
add to whitelist

**Comment by reaperhulk** [comment]
confirmed the vector fix against latest NIST CAVP data.

**Comment by alex** [comment]
Why was our original vector wrong?

On Thu, Apr 30, 2015 at 12:34 PM, Paul Kehrer <notifications@github.com>
wrote:

> confirmed the vector fix against latest NIST CAVP data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1876#issuecomment-97871259>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
I'm unsure. I confirmed it at the time (see #1264), but it wouldn't surprise me to learn that NIST updated the files to fix this.

**Comment by public** [comment]
It is rather suspicious that both files have the exact same defect.

**Comment by simo5** [comment]
I couldn't find the same file on NIST websites.
I can only find files with no [EA] set anymore and they also have assitional parameters.
Where did you get the original files from ?

**Comment by reaperhulk** [comment]
http://csrc.nist.gov/groups/STM/cavp/documents/keymgmt/KASTestVectorsECC2014.zip should be the original source, but yeah...the EA set appears to be missing now?

**Comment by public** [comment]
The PR that added them was #879 from April 2014 but the timestamps on all the files in that zip are from December 2014 so they definitely regenerated a bunch of stuff.

**Comment by simo5** [comment]
Added new test vestors from NIST that include KDF after raw ECDH vectors.
Changed slightly the vector loader to reflect be compatible with both the newer and older files and load only the fields used in #1882 for testing.
Also changed how fail/pass is recorded so tests can check exactly what should go wrong if they can/care.

**Comment by reaperhulk** [comment]
The new test vectors should be put into a separate PR so we can confirm they match the NIST download and merge them separately. Thanks!

**Comment by simo5** [comment]
ok #1884 it is

**Comment by public** [comment]
Remove the actual vectors from this PR please.

**Comment by simo5** [comment]
On Sun, 2015-05-03 at 03:30 -0700, Alex Stapleton wrote:
> Remove the actual vectors from this PR please.

I am not sure what you mean, you want me to remove the test vectors that
test the function that loads the vector files ?

-- 
Simo Sorce * Red Hat, Inc * New York

**Comment by reaperhulk** [comment]
This LGTM. Any outstanding comments @public?

**Pull request merged**
