### PR TITLE
what happens if we do this

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Didn't work :) (Worth a shot though!)

**Comment by markokr** [comment]
It did not crash on arm64... Instead some amd64-s had random error.

**Comment by reaperhulk** [comment]
Yeah it ignored the key and booted on an x86_64 builder. Presumably we have to be allowlisted to use that key (which is not publicly stated yet, I spotted it in a travis commit).

**Comment by markokr** [comment]
Heh, that was indeed sneaky.

**Pull request closed without merging**
