### PR TITLE
Adding elliptic curve test fixtures

### PR DESCRIPTION
**Pull request by PeterHamilton**
This change adds pre-generated elliptic curve keys to be used in elliptic curve tests.

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by PeterHamilton** [comment]
What's the best way to resolve coverage for these fixtures? I don't just want to add arbitrary tests to cover testing data. I'm planning on using some of these fixtures in my subsequent certificate validation patch, but that doesn't address current coverage.

**Comment by alex** [comment]
If you could replace one tests generate or load-from-vector using one of
these vlaues, that'd work.

On Thu, Oct 29, 2015 at 1:44 PM, Peter Hamilton <notifications@github.com>
wrote:

> What's the best way to resolve coverage for these fixtures? I don't just
> want to add arbitrary tests to cover testing data. I'm planning on using
> some of these fixtures in my subsequent certificate validation patch, but
> that doesn't address current coverage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2458#issuecomment-152262299>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by PeterHamilton** [comment]
Hmm, older versions of OpenSSL don't support elliptic curves. I'll find a better test to tweak.

**Comment by PeterHamilton** [comment]
Not entirely sure why the build failed. It looks like there was a problem with the logging when setting up the Travis run. It didn't happen consistently across the different builds either.

**Comment by alex** [comment]
@PeterHamilton looks like it's a bug in PyPy's nightly. I'm investigating, otherwise this patch lgtm.

**Comment by reaperhulk** [comment]
How did you generate these? I'm assuming with ec.generate_key and then calling the `numbers` methods?

**Comment by PeterHamilton** [comment]
@reaperhulk I actually used OpenSSL and then dumped the numbers via `serialization.load_pem_private_key` and `load_pem_public_key`. Kind of roundabout but it worked.

**Comment by reaperhulk** [comment]
Okay, that's fine. Verified these load into keys so :+1:

**Pull request merged**
