### PR TITLE
add binding for d2i_GENERAL_NAMES()

### PR DESCRIPTION
**Pull request by etrauschke**
These are the bindings needed for #2315

### CODE REVIEW

**Comment by reaperhulk** [comment]
LGTM

**Comment by reaperhulk** [comment]
@stevepeak is there an issue with codecov's status API reporting? This PR has been waiting for codecov to update for about 2 hours now. (As a side note, would it be possible to publish a statuspage.io style page for codecov so we can check to see if you're already aware of degraded service?)

**Comment by alex** [comment]
WELL TIMED

**Comment by reaperhulk** [comment]
...within like 2 minutes!

**Comment by stevepeak** [comment]
@reaperhulk [Codecov Status Page](http://status.codecov.io/) sometime the job queue piles up. I'm working on optimization strategies. We should start seeing delays like this occur less often. Thank you

**Comment by reaperhulk** [comment]
Thanks Steve, we appreciate the update. I'll keep an eye on the status page going forward :)

**Comment by stevepeak** [comment]
Awesome! PS we do have active chat support on IRC #codecov and [Gitter](https://gitter.im/codecov/support). I'm also working hard on our next gen UI... I'm so pumped to show it to everyone!

**Pull request merged**
