### PR TITLE
issue-2524

### PR DESCRIPTION
**Pull request by nbastin**
- Allows for any OID in access_method
- Validates OIDs at creation time
- Cleaned up all tests which used illegal OID values (other than those that should)
- Added a test for arbitrary access_method OIDs

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by reaperhulk** [comment]
Could you add a test verifying that we can successfully encode arbitrary OIDs using the CertificateBuilder? It should work fine with the current OpenSSL code, but a test will make sure we don't regress with other backends in the future.

Also, there are rules for OID values thanks to ASN.1 BER encoding, so we probably need to validate that. I believe the rules are that the second part cannot exceed 39 and the first must be {0, 1, 2}. If you attempt to encode values that violate this constraint in OpenSSL using `OBJ_txt2obj` (which is what we use under the covers to translate `ObjectIdentifier` when constructing certificate payloads) you'll get back a null pointer.

**Comment by alex** [comment]
The ruels are
https://github.com/alex/rust-asn1/blob/master/src/utils.rs#L16-L18


On Sun, Dec 13, 2015 at 11:30 AM, Paul Kehrer <notifications@github.com>
wrote:

> Could you add a test verifying that we can successfully encode arbitrary
> OIDs using the CertificateBuilder? It should work fine with the current
> OpenSSL code, but a test will make sure we don't regress with other
> backends in the future.
>
> Also, there are rules for OID values thanks to ASN.1 BER encoding, so we
> probably need to validate that. I believe the rules are that the second
> part cannot exceed 39 and the first must be {0, 1, 2}. If you attempt to
> encode values that violate this constraint in OpenSSL using OBJ_txt2obj
> (which is what we use under the covers to translate ObjectIdentifier when
> constructing certificate payloads) you'll get back a null pointer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2525#issuecomment-164274214>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by nbastin** [comment]
@reaperhulk I'm not sure what test you're asking for re: CertificateBuilder, or at least how this would different from what TestObjectIdentifier already does (this is my first foray into the code, so perhaps there is something obvious here I simply don't understand).

Also, I wasn't trying to write a fully compliant ASN.1 parser, just adding some basic sanity check as previously you could make an OID of "foo" or "notanoid", or similar nonsense.  Perhaps really the library should pull in something like `pyasn1` rather than trying to reinvent the wheel across the board.

**Comment by nbastin** [comment]
Test added as discussed on IRC.

**Comment by reaperhulk** [comment]
Thanks for the test @nbastin. As @alex mentioned in IRC, would you mind opening a separate PR for the `__init__` change (plus adding the limited validation around encodable OIDs we mentioned earlier in this PR)? We can review/merge that and then rebase this change to be solely the expansion of support for arbitrary OIDs in AIA. Sorry about the extra work; we appreciate your efforts thus far!

**Comment by nbastin** [comment]
Separate OID PR as 2530.

**Comment by reaperhulk** [comment]
This can now be rebased/merged to resolve the conflicts. Also, @nbastin if you want to add yourself to `AUTHORS.rst` in a separate PR please feel free to do so!

**Pull request merged**
