### PR TITLE
reorganize x509 extension docs and add information about ExtensionType

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by reaperhulk** [comment]
This fixes #2223

**Comment by reaperhulk** [comment]
jenkins, retest this please

**Comment by alex** [comment]
oof, I'm not sure the "confirms to the ExtensionType interface" comments add a lot of value here. I'm struggling to imagine a situation where that comment helps a person.

**Comment by reaperhulk** [comment]
@alex We need a way to say "these are the actual classes you should pass to `Extension` or `add_extension` and I'm not sure what that looks like :(

**Comment by reaperhulk** [comment]
Closing this as I think splitting the x509 module will make it easier to logically group items in our docs soon.

**Pull request closed without merging**
