### PR TITLE
Try using the rust cache action

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Well it looks like it works, but what are we getting/losing here? 😄

**Comment by alex** [comment]
This is in a theoretical sense worse than sccache, but it won't blow the rate limit, so it will actually work.

Notably it doesn't cache local package, so we'll be rebuilding _our_ packages every build, but effectively never rebuilding our dependencies.

Downside is we're back to manual management of cache keys.

**Comment by reaperhulk** [comment]
Love to churn our caching techniques.

**Comment by alex** [comment]
Indeed.

If Github 10x'd their GHA cache rate limit quota, this would not be necessary.

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
