### PR TITLE
Make the code compatible with the latest sphinx release

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
... apparently spell check no longer believes in contractions: https://jenkins.cryptography.io/job/cryptography-pr-docs/2804/console

**Comment by alex** [comment]
I assume this is an unintended consequence of the new sphinx version. @dhellmann are you seeing this / do is there a workaround, or shall we wait for a fix?

(@reaperhulk, we may want to pin sphinx, as I suspect we're going to want to get some dev work done at PyCon!)

**Comment by reaperhulk** [comment]
Yeah pinning seems like a good idea for the moment.

**Comment by alex** [comment]
Filed https://bitbucket.org/dhellmann/sphinxcontrib-spelling/issues/13/with-sphinx-161-contractions-result-in

**Comment by reaperhulk** [comment]
What is this doing now? I don't know anything about the sphinx 1.6.1 breakage other than it appears to be extremely widespread :)

**Comment by alex** [comment]
Not sure I understand the question, this code works on both 1.6.1 and <1.6.1.

Basically I inlined the contents of `make_admonition` into out code and then constant propagated.

**Comment by alex** [comment]
(This code being "this PR")

**Comment by reaperhulk** [comment]
Okay, makes sense. I can look at that then. We're still blocked on the spellcheck issue though, correct?

**Comment by alex** [comment]
Yes, but that blocks #3545, not this.

**Pull request merged**
