### PR TITLE
Update wheel scripts to match what Jenkins has

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
We never completed the switch to using these scripts in jenkins, so we should pull the latest from jenkins (for both windows and macOS, which both have been updated to do compile against 1.1.0 and generate py3.6 wheels), merge that, then switch the wheel builder to clone the repo and call the scripts.

**Comment by alex** [comment]
Will this need to be backported to the release branch?

**Comment by reaperhulk** [comment]
Not necessarily. If we have the wheel builder clone master to run the script we'll be fine on branches. The builder pulls the sdist from pypi so it doesn't use any local checkout.

**Comment by alex** [comment]
👍

**Pull request merged**
