### PR TITLE
Add urllib3 to downstream tests

### PR DESCRIPTION
**Pull request by jlaine**

### CODE REVIEW

**Comment by jlaine** [comment]
Don't trust the "ok" on the tests, since Jenkins did not pick up the modified Jenkinsfile

**Comment by jlaine** [comment]
Can we merge this if urllib3 is now unbroken?

**Comment by reaperhulk** [comment]
I need to hijack it and submit it as a PR to verify that it all works before we can merge.

**Comment by jlaine** [comment]
Sounds good. If you're wondering about the [socks] bit I blindly copied it over from pyopenssl's downstream test.

**Pull request closed without merging**
