### PR TITLE
Switch from ourborous to self_cell

### PR DESCRIPTION
**Pull request by alex**
The motivation here is hopefully (?) to reduce compilation times.

### CODE REVIEW

**Comment by alex** [comment]
We measured this and it's a 10-15% compilation time win at `-j2`, but no win on media-01 with no `-j`.

Based on this we're going to hold on considering this for merge, to see what other build time optimizations are available, and how we feel about the relative maintenance of `ouroborous` and `self_cell`.

**Comment by Voultapher** [comment]
I've recently released version 1.0. I'd say the project is pretty stable and I plan to address any upcoming issues.

**Comment by alex** [comment]
My plan for this is, once pyo3 upgrades to syn 2, we'll rebase this to see
the wins of getting down to a single version of syn

**Comment by alex** [comment]
Due to https://rustsec.org/advisories/RUSTSEC-2023-0042.html, I think we should re-consider this for merging.

**Comment by reaperhulk** [comment]
Well, if the maintainer has abandoned ouroboros due to this it's hard to argue against migration 😄

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
