### PR TITLE
Fix for #8854

### PR DESCRIPTION
**Pull request by harmin-parra**
Fix for issue #8854

### CODE REVIEW

**Review by alex — COMMENTED** [review]
Please document this in `docs/x509/reference.rst`, thanks.

**Comment by harmin-parra** [comment]
See https://github.com/pyca/cryptography/pull/8860

**Comment by reaperhulk** [comment]
That separate PR should just be another commit on this one 😄

**Comment by harmin-parra** [comment]
I am new using PR and commits.
I dont know how to merge the 2 into 1 PR

**Review by alex — APPROVED** [review]

**Pull request merged**
