### PR TITLE
add strip to some tests because we don't care about newlines

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
I'm not convinced strip is correct here, I feel like we should make a guarntee about what the backend emits in terms of newlines.

**Comment by reaperhulk** [comment]
I'd be willing to strip in the backend such that our "guarantee" is that backends don't return leading or trailing newlines.

**Comment by public** [comment]
Should it not be the other way around? That we should make sure backends always return PEM with a trailing new line?

**Comment by alex** [comment]
I think I agree, returning a result with a single trailing `\n` makes sense.

On Sat, Mar 28, 2015 at 2:26 PM, Alex Stapleton <notifications@github.com>
wrote:

> Should it not be the other way around? That we should make sure backends
> always return PEM with a trailing new line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1792#issuecomment-87278988>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
I'm interested in why it should matter to people if there's a trailing newline or not? Is the idea that people are going to write multiple keys/certs to the same output file? There are several software packages that do ask you to concat cert+key I guess.

**Comment by alex** [comment]
Concatenating certs, placing them in plaintext formatted media, hell just
printing it out to stdout.

On Thu, Apr 2, 2015 at 8:32 AM, Paul Kehrer <notifications@github.com>
wrote:

> I'm interested in why it should matter to people if there's a trailing
> newline or not? Is the idea that people are going to write multiple
> keys/certs to the same output file? There are several software packages
> that do ask you to concat cert+key I guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1792#issuecomment-88898405>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by public** [comment]
It's not entirely clear in the RFC but it does seem to imply that stuff should be new line terminated to me.

**Comment by schlenk** [comment]
This is similar to issue #1790. I think the fix in PR #1817 is better way to handle this case.

**Pull request closed without merging**
