### PR TITLE
Converted DER parsing of SPKIs to rust

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Do we have tests that verify that this generates the same values? Looking at `from_public_key` it doesn't look like our test for this asserts on a specific value.

**Comment by alex** [comment]
There's a handful of tests -- e.g. `test_from_dsa_public_key` in `test_x509_ext.py` checks that it matches what's in a cert. That's against a fixed value.

**Comment by alex** [comment]
There's also versions of that for ed25519 and ed448

**Comment by reaperhulk** [comment]
Ah, yes, okay. 👍

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
