### PR TITLE
Try to fix the aws-encryption-sdk tests

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by mattsb42-aws** [comment]
A proper fix is in process here: https://github.com/aws/aws-encryption-sdk-python/pull/256

**Comment by alex** [comment]
You think that's likely to land this evening? I was about to ask if the office was already cleared out... but I guess that question isn't very relevant these days.

**Comment by mattsb42-aws** [comment]
Yeah, I'll make sure it lands this evening; looks like I missed something, but I'll get that sorted asap.

**Comment by alex** [comment]
Thanks. I'll go ahead and close this then.

**Pull request closed without merging**
