### PR TITLE
Complete removal of py2

### LINKED ISSUE #5359: Python 2.7 support timeline
We deprecated 2.7 support in our 3.0 release, but we're blocked on very significant performance improvements in our CI (https://github.com/pyca/cryptography/pull/5246) by continued 2.7 support. This issue is just to discuss and track when we're going to actually drop support. At the moment we continue to see ~20% of our downloads come from Python 2 (I haven't tried to run the numbers on the latest release so that's just a total across all possible versions).

I'd also like to see what our downstream consumers are thinking about regarding 2.7 support in their own projects. /cc @bmw @mattsb42-aws @glyph @bitprophet.

### PR DESCRIPTION
**Pull request by alex**
fixes #5359

Note: did not remove all the `__future__` imports, and there's no changelog entry.

### CODE REVIEW

**Comment by reaperhulk** [comment]
When we're ready to land this let's split this up into multiple PRs.

**Comment by alex** [comment]
For future alex, the parts to break this into:

- [ ] Drop from CI, remove anything necessary for coverage
- [ ] Drop usage of `six`
- [ ] Change `black` target version to 3.6
- [ ] Drop all the `__future__` imports

**Comment by penguinolog** [comment]
You can use isort for dropping `__future__`

**Comment by Cartoon3636** [comment]
👍👍👍👍

**Review by reaperhulk — APPROVED** [review]

**Comment by reaperhulk** [comment]
Needs rebase

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
