### PR TITLE
Migrate ChaCha20Poly1305 AEAD to Rust

### PR DESCRIPTION
**Pull request by alex**
- [x] BoringSSL support
- [x] Re-use ctx
- [x] https://github.com/sfackler/rust-openssl/pull/2011

### CODE REVIEW

**Comment by alex** [comment]
Grumble, not working due to https://github.com/openssl/openssl/issues/21853

**Comment by alex** [comment]
This disable ctx reuse on OpenSSL 3.0-3.2. There's a bunch of code we can delete once we support only versions with workign copies.

Even with the ctx reuse disabled on 3.0.2, which is used in the benchmarks, it's 20% faster than main.

**Comment by reaperhulk** [comment]
Do we use fixedpool anywhere now that this PR removes it from chacha?

**Comment by alex** [comment]
Nope. Will remove it.

**Review by reaperhulk — APPROVED** [review]

**Comment by reaperhulk** [comment]
I do not envy future us looking at those conditionals.

**Pull request merged**
