### PR TITLE
Attempt to enable coverage on pypy

### LINKED ISSUE #785: Re-enable coverage on pypy.
One day maybe, pypy will be able to run code with coverage in a reasonable period of time.

Previously this was pull request #209 but having this sitting in an open pull request is not actually very useful.

### PR DESCRIPTION
**Pull request by alex**
Fixes #785

### CODE REVIEW

**Comment by reaperhulk** [comment]
Well this does work now (big improvement over timing out the build because it took >50 min!). Makes pypy on OS X take 16-24 minutes though.

**Comment by alex** [comment]
Yeah, that's pretty cruddy, is there a fixed point we want to hold out for?
I think this is realistic. I think if we reordered the OS X builds to go
before Linux builds we'd also get a reduction in overall build time

On Sun, Nov 1, 2015 at 4:28 PM, Paul Kehrer <notifications@github.com>
wrote:

> Well this does work now (big improvement over timing out the build because
> it took >50 min!). Makes pypy on OS X take 16-24 minutes though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2463#issuecomment-152865202>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
I'd like to see it take less time than python 2.6 before we turn it on.

We've reordered in the past and we had issues with the mac builders stalling and then the linux builders wouldn't run (when we wanted quicker feedback). Maybe a solution is to move the mac builds up but have one 2.7, one 3.5 and a linux docs job run at the very top.

**Comment by alex** [comment]
We already have jenkins for basic validation, is there a reason not to let
that be our quick feedback?

On Sun, Nov 1, 2015 at 5:16 PM, Paul Kehrer <notifications@github.com>
wrote:

> I'd like to see it take less time than python 2.6 before we turn it on.
>
> We've reordered in the past and we had issues with the mac builders
> stalling and then the linux builders wouldn't run (when we wanted quicker
> feedback). Maybe a solution is to move the mac builds up but have one 2.7,
> one 3.5 and a linux docs job run at the very top.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2463#issuecomment-152869576>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
Good point -- I added the pep8 and docs jobs to jenkins specifically to give rapid feedback on that front. So then reordering is not necessarily a bad idea. In high queue situations it won't speed things up much, but it should shorten the total wall clock time for individual builds.

**Comment by alex** [comment]
jenkins retest this please

**Comment by reaperhulk** [comment]
Could we have it skip coverage on OS X pypy? That would avoid most of the performance penalty (23 minutes on OS X pypy due to the two backends) and I'd be happy to merge then (especially as we've now got two PRs that need pypy coverage)

**Comment by reaperhulk** [comment]
This was superseded by #2638

**Pull request closed without merging**
