### PR TITLE
add SM2 support under OpenSSL 3.x

### PR DESCRIPTION
**Pull request by mr-m0nst3r**
Hi there, I've added SM2 support to the library, it's becoming more and more widely used in China, and this cryptography library is amazing, can't help to submit this PR, hope everything would go well.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Thanks for trying to contribute, but adding SM2 support involves quite a bit more work than this PR has done so far. Someone needs to design and implement the right APIs for SM2Sign and also ensure our ECDSA APIs reject SM2. https://github.com/pyca/cryptography/pull/5894 was a past attempt, but it stalled out. If you'd like to take on that work we'd be happy to review.

**Comment by mr-m0nst3r** [comment]
thank you for your review, haven't noticed that part yet, I'll try later. thank you.

**Comment by mr-m0nst3r** [comment]
Hi there, I'm stuck at finishing this PR. Problem is:

I change `src/cryptography/hazmat/primitives/asymmetric/ec.py` by adding `_CURVE_TYPES`:
```
_CURVE_TYPES: typing.Dict[str, typing.Type[EllipticCurve]] = {
    "prime192v1": SECP192R1,
    "prime256v1": SECP256R1,
    "secp192r1": SECP192R1,
    "secp224r1": SECP224R1,
    "secp256r1": SECP256R1,
    "secp384r1": SECP384R1,
    "secp521r1": SECP521R1,
    "secp256k1": SECP256K1,
    "sect163k1": SECT163K1,
    "sect233k1": SECT233K1,
    "sect283k1": SECT283K1,
    "sect409k1": SECT409K1,
    "sect571k1": SECT571K1,
    "sect163r2": SECT163R2,
    "sect233r1": SECT233R1,
    "sect283r1": SECT283R1,
    "sect409r1": SECT409R1,
    "sect571r1": SECT571R1,
    "brainpoolP256r1": BrainpoolP256R1,
    "brainpoolP384r1": BrainpoolP384R1,
    "brainpoolP512r1": BrainpoolP512R1,
    "sm2": SM2,
}
```

Add `key_type` to `src/cryptography/hazmat/backends/openssl/backend.py`:
```
        elif key_type == self._lib.EVP_PKEY_SM2:
            # Add sm2 support
            return rust_openssl.ec.private_key_from_ptr(
                int(self._ffi.cast("uintptr_t", evp_pkey))
            )
        else:
            raise UnsupportedAlgorithm("Unsupported key type.")
```

BUT still see an error:
```
File "/Users/m0nst3r/venvs/test/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 566, in _evp_pkey_to_private_key
    return rust_openssl.ec.private_key_from_ptr(
cryptography.exceptions.UnsupportedAlgorithm: SM2 is not a supported elliptic curve
```

It's caused by the following code:
``` src/rust/src/backend/ec.rs
    Ok(py
        .import(pyo3::intern!(
            py,
            "cryptography.hazmat.primitives.asymmetric.ec"
        ))?
        .getattr(pyo3::intern!(py, "_CURVE_TYPES"))?
        .extract::<&pyo3::types::PyDict>()?
        .get_item(name)
        .ok_or_else(|| {
            CryptographyError::from(exceptions::UnsupportedAlgorithm::new_err((
                format!("{} is not a supported elliptic curve", name),
                exceptions::Reasons::UNSUPPORTED_ELLIPTIC_CURVE,
            )))
        })?
        .call0()?)
}
```

But I've added the types, stuck here.
Here's the testing code:
```
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives import serialization
# private_key = ec.generate_private_key(ec.SM2())
loaded_private_key = None
# # write pem
# pripem = private_key.private_bytes(encoding=serialization.Encoding.PEM, format=serialization.PrivateFormat.TraditionalOpenSSL, encryption_algorithm=serialization.NoEncryption())
# with open('pri.pem', 'wb') as f:
#     f.write(pripem)
#
# pubpem = private_key.public_key().public_bytes(encoding=serialization.Encoding.PEM, format=serialization.PublicFormat.SubjectPublicKeyInfo)
# with open('pub.pem', 'wb') as f:
#     f.write(pubpem)

with open("pri.pem", 'rb') as f:
    loaded_private_key = serialization.load_pem_private_key(f.read(), password=None)

numbers = loaded_private_key.private_numbers()
pn = numbers.public_numbers
print("private_value", numbers.private_value)
print("pn.x", pn.x)
print("pn.y",pn.y)
print("pn.public_key()",pn.public_key())

```

Haven't coded anything using rust, I think I'm missing something, can you point out a direction to continue?

**Comment by reaperhulk** [comment]
SM2 should not be considered a curve like the rest of the curves in cryptography because it is not signed in the same fashion. It should instead be considered an entirely separate curve type that is only compatible with `SM2Sign` (an API that does not yet exist but needs to for SM2 to land). This is non-trivial work and you'd be better served looking carefully at how everything works now and then proposing those new APIs.

Significant chunks of this code are in rust as well, so unfortunately some comfort with the language will be needed.

**Comment by mr-m0nst3r** [comment]
I've figured out the problem, because in openssl's `_CURVE_TYPES`, it's `SM2`, not `sm2`.

I've also implemented SM2Sign like ECDSA, and the sign is working.

But can't `load_pem_public_key`, it's reporting `UnsupportedAlgorithm("Unsupported key type.")`.

Investigating this the who day, still having no clue at all.

Do you have any suggestions?

In line 725 of `backend.py`,
```
if evp_pkey != self._ffi.NULL:
            evp_pkey = self._ffi.gc(evp_pkey, self._lib.EVP_PKEY_free)
            return self._evp_pkey_to_public_key(evp_pkey)
```

the `evp_pkey` is `-1`.
seems that `self._ffi.gc` is the point.
But I don's see any source code, or, would like to point me to the right source file?

Thank you mate.

**Comment by mr-m0nst3r** [comment]
I'm closing this, this may not be the right way to do it. There're no `encrypt` for `ec`, but it's there for `rsa`. I maybe misunderstanding some concepts. Sorry

**Pull request closed without merging**
