### PR TITLE
ECDH take 4

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Since we've been rapidly evolving this API and it's come partially back around I'd like @ronf to weigh in on whether he's happy with this.

**Comment by ronf** [comment]
Is there a summary somewhere of the latest proposal? From the file diff, it looks like we're back to an exchange() method on the private key object rather than passing the key to the ECDH() object, but that exchange() covers both what exchange() and agree() did before. I'm ok with that, though I think passing the keys to ECDH() would have been cleaner. I also don't see a good way to do ephemeral DH or ECDH with this style of API, other than for the caller to be responsible for creating the ephemeral keys explicitly each time.

In this version, is the KDF removed entirely? I didn't see that showing up any more.

**Comment by reaperhulk** [comment]
Correct ,the KDF is removed entirely.

ECDHE in this system would require a new ec key to be generated each time and then used to `exchange`. That does require a reasonable understanding of the mechanics of ECDHE though.

I am neutral on ECDH class vs this, but I'd be interested in knowing your reasoning for preferring a standalone class.

**Comment by alex** [comment]
FWIW, I don't think ECDHE deserves special support, it's not a distinct
algorithm.

On Mon, Oct 19, 2015 at 2:57 PM, Paul Kehrer <notifications@github.com>
wrote:

> Correct ,the KDF is removed entirely.
>
> ECDHE in this system would require a new ec key to be generated each time
> and then used to exchange. That does require a reasonable understanding
> of the mechanics of ECDHE though.
>
> I am neutral on ECDH class vs this, but I'd be interested in knowing your
> reasoning for preferring a standalone class.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2427#issuecomment-149312448>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by ronf** [comment]
I'm good with the KDF removal. That can easily be handled after the shared key data is returned.

As for ECDHE, the discussion proposed two options: One was a subclass of ECDH() with a different constructor but no other child methods, and another was to use a class method to achieve that. Both took an algorithm and backend instead of the private key itself. If we don't want whole separate class, the second option seemed like a good approach to me.

That said, the difference really is pretty minor. As long as both DH and ECDH support a top-level "generate_private_key()" method, I think this works, and is an improvement over the original exchange/agree proposal. I'm good with it.

**Comment by reaperhulk** [comment]
Okay, I'm happy enough with this that I'll go ahead and merge. Thanks for your hard work on this @simo5 (and @alex) I'm going to file a follow up issue to write some docs for how to do ECDHE utilizing this API.

**Comment by ronf** [comment]
I updated my local copy of AsyncSSH to use the new API, and it appears to be working. Here's what I ended up with to match the internal API I previously defined. The "_curves" dictionary maps byte-string curve names to PyCA objects (allowing me to swap this for another backend easily without changing the calling code):

```python
class ECDH:
    """A shim around PyCA for ECDH key exchange"""

    def __init__(self, curve_id):
        try:
            curve, _ = _curves[curve_id]
        except KeyError: # pragma: no cover, other curves not registered
            raise ValueError('Unknown EC curve %s' %
                             curve_id.decode()) from None

        self._priv_key = ec.generate_private_key(curve, backend)
        self._keylen = (curve.key_size + 7) // 8

    def get_public(self):
        """Return the public key to send in the handshake"""

        pub = self._priv_key.private_numbers().public_numbers
        return encode_ec_point(self._keylen, pub.x, pub.y)

    def get_shared(self, peer_public):
        """Return the shared key from the peer's public key"""

        x, y = decode_ec_point(self._keylen, peer_public)
        pub = ec.EllipticCurvePublicNumbers(x, y, self._priv_key.curve)
        peer_key = pub.public_key(backend)
        shared_key = self._priv_key.exchange(ec.ECDH(), peer_key)
        
        return int.from_bytes(shared_key, 'big')
```

Cryptography is missing functions to encode/decode EC point values as byte strings (see #2346) so I had to provide that myself. However, the rest was pretty straightforward.

**Pull request merged**
