### PR TITLE
Name constraints ossl

### PR DESCRIPTION
**Pull request by reaperhulk**
Turns out the ipaddress module is...not great. Interested in a better approach to building the IPv{4,6}Network objects if anybody can come up with one.

depends on #2083 
refs #1947

### CODE REVIEW

**Comment by alex** [comment]
Can be rebased

**Comment by alex** [comment]
Can we split the changes to parsing `GENERAL_NAMES` out from adding name constraint support?

**Comment by reaperhulk** [comment]
We could do that by adding a few more NC test vectors that don't have the issues that require the GENERAL_NAMES modification. I'll put some vectors together for that.

**Comment by alex** [comment]
Ok, thanks. They feel like two distinct changes.

On Sun, Jun 28, 2015 at 10:52 PM, Paul Kehrer <notifications@github.com>
wrote:

> We could do that by adding a few more NC test vectors that don't have the
> issues that require the GENERAL_NAMES modification. I'll put some vectors
> together for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2084#issuecomment-116397588>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
rebase required

**Pull request merged**
