### PR TITLE
Add ASN.1 bindings for ASN1_TIME_set_string

### PR DESCRIPTION
**Pull request by sholsapp**
This will help make the API a little less annoying when dealing with
CRL re: https://github.com/pyca/pyopenssl/issues/256

### CODE REVIEW

**Comment by alex** [comment]
lgtm, will merge once tests pass

**Comment by sholsapp** [comment]
Thanks. Sorry for all the individual PR... the more time I spend with CRL the more things I see that need cryptography bindings. :smile:

**Comment by alex** [comment]
Ugh, I lied. It looks like this was added in OpenSSL 0.9.8k so not all supported platforms have it.

And I don't mind about all the individual PRs, makes them easier to review

**Comment by sholsapp** [comment]
@alex I didn't know about the OpenSSL 0.9.8k bit. Is there a way to handle this in code, or should I find another way to do what I want without *this* particular binding?

**Comment by alex** [comment]
It's possible to make the binding optional, but I don't think that'll acheive the goal you want, since then it'll just be missing

**Comment by alex** [comment]
Basically, if it's possible to implement the feature without this function, that'd be better.

**Comment by sholsapp** [comment]
I'll find another way to do what I want without this particular binding using pyOpenSSL's `OpenSSL.crypto._set_asn1_time` function.

I'm discarding this PR for now.

**Pull request closed without merging**
