### PR TITLE
Fixes #2856 -- add a fast path to _key_identifier_from_public_key for RSA keys

### LINKED ISSUE #2856: _key_identifier_from_public_key is pretty slow
Sure, okay, it even has a comment warning about this: https://github.com/pyca/cryptography/blob/master/src/cryptography/x509/extensions.py#L35

I just ran into this in the context of doing some testing; the bulk of the runtime in the test is issuing certificates in my fake CA, as part of that I'm using `SubjectKeyIdentifier.from_public_key` and `AuthorityKeyIdentifier.from_issuer_public_key`; I can cache the latter, but not the former.

### PR DESCRIPTION
**Pull request by alex**
And I'm a reasonably certain this is correct :-)

### CODE REVIEW

**Comment by alex** [comment]
Appears to be ~100x faster (o_O)

**Comment by mithrandi** [comment]
I can confirm that this speeds things up a lot; only for RSA keys, of course.

**Comment by reaperhulk** [comment]
RSA path looks good, haven't looked at the EC path yet.

**Comment by reaperhulk** [comment]
EC path :+1: as well.

**Pull request merged**
