### PR TITLE
Add --no-cache-dir when building static wheels.

### PR DESCRIPTION
**Pull request by Lukasa**
Per @geradcoles suggestion in #2338 and certifi/python-certifi#26.

### CODE REVIEW

**Comment by alex** [comment]
cc: @dstufft

**Comment by reaperhulk** [comment]
Should it be this flag or `--no-use-wheel`?

**Comment by Lukasa** [comment]
That's a good question: @dstufft would know.

**Comment by dstufft** [comment]
Probably you want ``--no-binary cryptography``, like:

```console
$ CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-binary cryptogrpahy cryptography
```

I think that will do what you want... although it only works in the latest pip, the ``--no-use-wheel`` version is deprecated but does the same thing (though it applies to everything and not just cryptography).

**Comment by dstufft** [comment]
Specifically, the ``--no-use-wheel`` version is more compat with older versions, but is deprecated in favor of ``--no-binary``.

**Comment by Lukasa** [comment]
@dstufft Is there any good reason not to use --no-use-wheel, then? I'm worried about providing instructions that only work with bleeding-edge pip.

**Comment by dstufft** [comment]
It'll go away at some point, but that's it.

**Comment by Lukasa** [comment]
Ok, I've switched to `--no-use-wheel` instead.

**Pull request merged**
