### PR TITLE
Switch to codecov

### PR DESCRIPTION
**Pull request by reaperhulk**
codecov is now fully working thanks to @stevepeak's hard work. Let's switch over!

Note: Since codecov has branch coverage we can now see that we are **not at 100%**. This means we can't set the status API to fail at 100% only right now. Fortunately, codecov supports a coverage on diff'd lines measurement so we can setting that to 100% while we work on covering the missed branches.

This supersedes #2070

### CODE REVIEW

**Comment by reaperhulk** [comment]
One slight hiccup, we can only require integral numbers for minimum coverage. So if we want the codecov checks to show up as passing in status API we have to set it to 99% until we get to 100%. @stevepeak is it possible to add decimal precision to that field?

**Comment by alex** [comment]
@reaperhulk if we've got 100% required for new/changed lines, it ought to work out right?

**Comment by reaperhulk** [comment]
@alex It should, yes.

**Comment by reaperhulk** [comment]
Hmm, would be very nice if codecov didn't report failure during the first few submissions from travis. coveralls seems to know when travis is done -- is that something that could be added to codecov @stevepeak?

**Comment by alex** [comment]
Personally I don't mind it.

**Comment by stevepeak** [comment]
Wow! Thank you my friends for your attention and patience. I feel very honored having Codecov in this project! :+1:

**Pull request merged**
