### PR TITLE
name constraints - support leading periods

### PR DESCRIPTION
**Pull request by reaperhulk**
Name Constraints may have leading periods.

refs #1947

### CODE REVIEW

**Comment by alex** [comment]
bleh, I don't understand the codecov results here. There's no way this patch has the claimed impact on coverage? /cc @stevepeak

**Comment by reaperhulk** [comment]
I canceled a previous build on this same PR and I bet codecov isn't handling that properly.

**Comment by alex** [comment]
Do you want to rebase and push or something; I can't merge with the coverage as is.

**Comment by reaperhulk** [comment]
I'll close this one and push up a renamed branch and see what we get

**Pull request closed without merging**
