### PR TITLE
RSA PKCS1 public key loading support

### PR DESCRIPTION
**Pull request by reaperhulk**
Requires a rebase once #1714 lands.

- [x] Changelog entry

### CODE REVIEW

**Comment by reaperhulk** [comment]
retest this please

**Comment by reaperhulk** [comment]
retest this please

**Comment by reaperhulk** [comment]
retest this please

**Comment by reaperhulk** [comment]
This is the next priority for 0.8 as the public serialize RSA PR will depend on it

**Comment by public** [comment]
LGTM

**Pull request merged**
