### PR TITLE
in OpenSSL 1.1.0 these EC functions are no longer const args

### PR DESCRIPTION
**Pull request by reaperhulk**
Fixes a warning

### CODE REVIEW

**Comment by reaperhulk** [comment]
@stevepeak We've been getting weird coverage reports fairly often lately. For example, this is definitely not the right coverage data for this PR. Are you aware of any issue on your end?

**Comment by alex** [comment]
Coverage is clearly misleading, going to merge on my own judgement.

**Comment by stevepeak** [comment]
Hey @alex I'll review these reports to see where the discrepancy is. But systems been stable quite some time as we are working on next major release. Thanks!

**Comment by alex** [comment]
Thanks Steve!

On Sun, Mar 13, 2016 at 10:35 PM, Steve Peak <notifications@github.com>
wrote:

> Hey @alex <https://github.com/alex> I'll review these reports to see
> where the discrepancy is. But systems been stable quite some time as we are
> working on next major release. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2823#issuecomment-196112099>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by stevepeak** [comment]
@alex here is what I've gathered:

The comment compared [76252fc](https://codecov.io/github/pyca/cryptography?ref=76252fc) (100%)...[82a4675](https://codecov.io/github/pyca/cryptography?ref=82a4675) (99.98%).

Here are some strange data:
- Compare [this](https://codecov.io/github/pyca/cryptography/src/cryptography/hazmat/backends/openssl/encode_asn1.py?ref=76252fca16dccc2add21c985d4d9d883ed55f1c9#l-544) against [this](https://codecov.io/github/pyca/cryptography/src/cryptography/hazmat/backends/openssl/encode_asn1.py?ref=82a46758ef223ad42c8b9add338cf38c6a80615b#l-543)
- [Here is your missed lines](https://codecov.io/github/pyca/cryptography/tests/test_x509.py?ref=82a46758ef223ad42c8b9add338cf38c6a80615b#l-2421)
- I'm seeing many lines of code that I'm not expecting to be measured by coverage (as seen in the file  above (line 2436 which is empty). I'll need to confirm this but these results come straight from the coverage.xml file produced. I've never seen inaccuracies like this before with coveragepy.

Upon all my findings...Codecov did its job perfectly. The comment and reports are accurate (given the processing of the coverage.xml files was correct). My next step is to download all 24 builds raw uploads and review them to confirm my suspicions of this being an issue with collecting coverage. I'm a little backlogged atm but I'll get back to this asap. Thanks!

**Pull request merged**
