### PR TITLE
Centralize declaration of docs and pep8 deps in setup.py

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
@reaperhulk does the jenkins pep8 machine also need a tox upgrade, or does it dislike the hyphen?

**Comment by alex** [comment]
(looks like it's a tox version issue)

**Comment by reaperhulk** [comment]
tox on that builder is 2.1.1 -- just upgraded to 2.3.1 now.

**Comment by alex** [comment]
jenkins, retest this please

**Comment by alex** [comment]
jenkins, retest this please

**Pull request merged**
