### PR TITLE
try running downstream tests with 3.11

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
@mattsb42-aws 👋, not sure if you're still the right person for this, but it looks like the test requirements.txt file in aws-encryption-sdk-python (https://github.com/aws/aws-encryption-sdk-python/blob/master/test/upstream-requirements-py37.txt) was originally built for py37, and hasn't been touched in a while. Are y'all able to either a) refresh that file, b) produce one that's intended for py311?

**Comment by mattsb42-aws** [comment]
I think @texastony is the one running point on those projects now. I'll poke the team.

**Comment by alex** [comment]
Thanks

**Comment by texastony** [comment]
@alex Acknowledged. 
I will either pick this up or pass this to the on-call.
If you have time, you could you cut us an issue?
If not, I should be able to keep this in my mind and get it done.

Is there a pressing timeline?

**Comment by alex** [comment]
I see you got to it already. Thanks!

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
