### PR TITLE
don't sort the serial numbers in a parsed CRL

### LINKED ISSUE #4456: get_revoked_certificate_by_serial_number breaks signature validation on CertificateRevocationList
Hi,

Using the `get_revoked_certificate_by_serial_number` method on CertificateRevocationList will make OpenSSL sort the content of the CRL, and thus changing it.

This can be demonstrated with the following snippet:

```
def main():
    with open("crl.crl", "rb") as open_file:
        crl = x509.load_der_x509_crl(open_file.read(), default_backend())

    print(base64.b64encode(hashlib.sha256(crl.tbs_certlist_bytes).digest()).decode())
    crl.get_revoked_certificate_by_serial_number(123)
    print(base64.b64encode(hashlib.sha256(crl.tbs_certlist_bytes).digest()).decode())
```

This will return two different hashes. This then makes the signature validation on the CRL fail (tried using both `tbs_certlist_bytes` and `is_signature_valid`).

Not a big deal (I'm guessing most will verify the signature on the CRL before checking if the certificate is in it), but I'm thinking a note in the documentation would be nice. I scratched my head quite a bit before understanding why a previously good CRL suddenly failed signature validation :-)

Thanks!

### PR DESCRIPTION
**Pull request by reaperhulk**
OpenSSL sorts them in place and this breaks the signature and more.

fixes #4456

### CODE REVIEW

**Comment by alex** [comment]
So, this is dumb. There's no reason to use the sorted version if we're going to dup the CRL; it results in sorting every single time, making this less efficient.

We need to either cache the copied-and-sorted CRL, or we should just write a simple for-loop in Python.

**Comment by alex** [comment]
You can save a few lines of code by splitting this out into a seperate method and using the `cached_property` decorator.

**Comment by reaperhulk** [comment]
I consistently forget that we have that decorator.

**Comment by alex** [comment]
How do you feel about issuing a point release for this?

**Comment by alex** [comment]
Something broken with the josepy tests

**Comment by reaperhulk** [comment]
It looks like our coverage pin is incompatible with pytest_cov at this point.

**Pull request merged**
