### PR TITLE
Expose extension data for UnsupportedExtension, issue #2901

### PR DESCRIPTION
**Pull request by rudolphfroger**

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by reaperhulk** [comment]
This will give you the value, but unfortunately since it raises an exception it will halt processing of all subsequent extensions (and won't give you previous ones either). This seems like it probably isn't what you actually want (e.g. in a certificate with 5 extensions, you'd only get the first unrecognized critical and would not have access to any of the others).

An alternate (but more involved) approach would be to come up with a public API for our extension parsing classes that allows users to register an OID and a callback. Something like

```python
def my_parser_func(data):
    // data is bytes, parse it however you need to
    a, b, c = parse_the_extension(data)
    return MyCustomExtensionClass(a, b, c)

x509.register_x509_extension(x509.ObjectIdentifier('1.2.3'), my_parser_func)

cert = x509.load_pem_x509_certificate(mypem, backend)
for ext in cert.extensions:
   print(ext)
```

With an approach like this you would see the instance of `MyCustomExtensionClass` be available in the `cert.extensions` iterable just like all the other extensions.

**Comment by rudolphfroger** [comment]
Yes, that would be much better. I'll try to come with a patch.

**Comment by alex** [comment]
Let's try to come up with an API that doesn't involve a global registry

**Comment by rudolphfroger** [comment]
How about a method on Certificate instances to register extra extension handlers on the instance (to be used before iterating over 'extensions')? The same probably applies to CertificateRevocationList, CertificateSigningRequest and RevokedCertificate. Something like
```python
cert = x509.load_pem_x509_certificate(mypem, backend)
cert.register_extension_handler(x509.ObjectIdentifier('1.2.3'), my_parser_func)
for ext in cert.extensions:
   print(ext)
```

**Comment by reaperhulk** [comment]
Having to register a handler every time you load a certificate seems like it would be annoying. In most cases users are presumably going to want repeated parsing to be capable of interpreting the same certificates. @alex do you have a suggestion? I was thinking maybe tying it to a backend, but that has complications with multibackend.

**Comment by alex** [comment]
I _think_ we want a public API version of the OpenSSL backend's
ExtensionParser idea.

On Fri, May 6, 2016 at 7:47 PM, Paul Kehrer <notifications@github.com>
wrote:

> Having to register a handler every time you load a certificate seems like
> it would be annoying. In most cases users are presumably going to want
> repeated parsing to be capable of interpreting the same certificates.
> @alex <https://github.com/alex> do you have a suggestion? I was thinking
> maybe tying it to a backend, but that has complications with multibackend.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2903#issuecomment-217588880>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by rudolphfroger** [comment]
I'm not familiar with OpenSSL's ExtensionParser idea is but we could add an API which extends the `*_HANDLERS` dicts of `cryptography/hazmat/backends/openssl/decode_asn1.py`

```python
x509.register_extension_parser(decode_my_ext, backend)
```

**Comment by alex** [comment]
We don't want the global state though, so you create a specific extension parser thing.

**Comment by frasertweedale** [comment]
Big +1 for a way to process critical unsupported extensions (along with all
other extensions).

Consider the story where someone wants to use python-cryptography to write
a certificate inspector / pretty-printer.  Processing cannot barf on critical but
unknown extensions.

I'm undertaking a refactor of FreeIPA's certificate processing code and this
is a blocker to using python-cryptography.

**Comment by rudolphfroger** [comment]
Alex mentioned an ExtensionParser class. I'm not sure what design he has in mind but I imagine it can be used to register extra extension parsers and which may be provided when parsing a certificate. This allows one to have multiple ExtensionParsers for different situations (i.e. no global extension parser registry).

Example:

```python
from cryptography.x509 import ExtensionParser

def my_parser_func(data):
    # data is bytes, parse it however you need to
    a, b, c = parse_the_extension(data)
    return MyCustomExtensionClass(a, b, c)

ext_parser = ExtensionParser()
ext_parser.register_extension_parser(x509.ObjectIdentifier('1.2.3'), my_parser_func)

cert = x509.load_pem_x509_certificate(mypem, extension_parser=ext_parser,
    backend=backend)

for ext in cert.extensions:
   print(ext)

def my_parser_func(data):
    # data is bytes, parse it however you need to
    x, y = parse_the_extension(data)
    return MyOtherCustomExtensionClass(x, y)

other_ext_parser = ExtensionParser()
other_ext_parser.register_extension_parser(x509.ObjectIdentifier('1.2.3'),
    my_other_parser_func)

other_cert = x509.load_pem_x509_certificate(my_other_pem, extension_parser=other_ext_parser,
    backend=backend)
```

**Comment by simo5** [comment]
A parser is fine, but you still need a "generic" parser that is a catchall if you do not have a specialized one. In some cases you just need to inspect certificates even if you do not understand the critical extension.

**Comment by rudolphfroger** [comment]
Adding a generic parser which just returns the ObjectIdentifier with the raw data would be trivial to add when an ExtensionParser interface would be available.

**Pull request closed without merging**
