### PR TITLE
Added bindings for SSL_renegotiate_<pending/abbreviated>

### PR DESCRIPTION
**Pull request by kjav**
This is to facilitate their use in the pyopenssl library.

### CODE REVIEW

**Comment by kjav** [comment]
Related to issue https://github.com/pyca/cryptography/issues/2300

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by reaperhulk** [comment]
jenkins, ok to test

**Comment by kjav** [comment]
@alex, I have a fork of the pyopenssl library which uses these bindings to add renegotiation functionality. When should I create the merge request? I'm worried the tests will fail as the cryptography version it uses might not be up to date with the changes in this merge.

**Comment by reaperhulk** [comment]
Once this merges you can open a PR against pyopenssl. There are tests there that run against cryptography master. The tests against the latest release version will fail, but that's expected for now.

**Comment by alex** [comment]
I don't think `SSL_renegotiate_abbreviated` exists in all versions of OpenSSL?

**Comment by kjav** [comment]
Do you have an example?

**Comment by reaperhulk** [comment]
Looks like it was added sometime in 1.0.1 so that'll have to be conditionally bound. @kjav look at the jenkins status check on this PR right now if you want to see where it's failing.

**Comment by kjav** [comment]
I added this binding on a whim - it is not required for the pyopenssl renegotiation support (the reason for this merge). I have removed it.

**Comment by kjav** [comment]
The checks have passed - can this be merged with master?

**Pull request merged**
