### PR TITLE
Drop support for Python 3.2

### PR DESCRIPTION
**Pull request by reaperhulk**
refs #1809

### CODE REVIEW

**Comment by hynek** [comment]
:+1:

**Comment by alex** [comment]
`setup.py` also needs to be updated

**Comment by alex** [comment]
Do we really want to do this with no deprecation period?

**Comment by dstufft** [comment]
I don't really think one is worth it, practically speaking zero people were using cryptography from Python 3.2 a few months ago and I have serious doubts that it saw a big rise in 3.2 users since that time. Is a deprecation warning for something that is actively holding back progress that (almost?) nobody is even going to encounter a useful deprecation warning?

If you want more numbers before merging this, I am redoing all of my graphs and I can generate cryptography specific ones again.

**Comment by alex** [comment]
If you could show the updated numbers, demonstrating that it's really
negligble, that'd be great.

On Tue, Apr 14, 2015 at 9:20 PM, Donald Stufft <notifications@github.com>
wrote:

> I don't really think one is worth it, practically speaking zero people
> were using cryptography from Python 3.2 a few months ago and I have serious
> doubts that it saw a big rise in 3.2 users since that time. Is a
> deprecation warning for something that is actively holding back progress
> that (almost?) nobody is even going to encounter a useful deprecation
> warning?
>
> If you want more numbers before merging this, I am redoing all of my
> graphs and I can generate cryptography specific ones again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1846#issuecomment-93133705>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
Sure!

**Comment by dstufft** [comment]
I have graphs now, these are specifically for cryptography so it should have relevant data. Both graphs represent the same data, the second one just zooms in on only Python 3.

stacked-py-pct

stacked-py3-pct

**Comment by alex** [comment]
Ok, I'm on board. Thanks for putting this together @dstufft !

**Comment by alex** [comment]
@reaperhulk Can you please also remove the relevant code from `install.sh`?

**Comment by alex** [comment]
Also, README, installation.rst, and docs/development/getting-started.rst

**Comment by reaperhulk** [comment]
retest this please

**Pull request merged**
