### PR TITLE
use pip install --user on travis

### PR DESCRIPTION
**Pull request by reaperhulk**
This attempts to use the Travis cache + wheels to speed up our builds a bit. Also dropped the use of sudo in favor of `pip install --user`.

### CODE REVIEW

**Comment by alex** [comment]
Travis's cache is only available with docker or paid plans, so this doesn't do anything.

**Comment by Ayrx** [comment]
`pip install --user` sounds like a good change though.

**Comment by reaperhulk** [comment]
Oops, didn't realize it was docker only. Nothing can ever speed up our builds :cry:

**Comment by reaperhulk** [comment]
Okay, altered track to just use `pip install --user`

**Comment by alex** [comment]
`pip install --user` doesn't install stuff in a place that's actually on `$PATH`. I think we should probaly just close this PR out.

**Comment by reaperhulk** [comment]
Yeah this isn't worth it for now.

**Pull request closed without merging**
