### PR TITLE
Removed provider language from asymmetric primitives docs

### PR DESCRIPTION
**Pull request by gorisaka**
Refs #3036

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by alex** [comment]
The examples which are just "A <foo>" are ok, it's only the "A <foo> provider" that need to be changed.

**Comment by gorisaka** [comment]
Certainly but, in my opinion, being consistent with the phrasing would be better.

**Comment by gorisaka** [comment]
But I can revise this PR.

**Comment by alex** [comment]
I think minimizing the PR to just removing the ones that say "provider" would be best.

**Comment by gorisaka** [comment]
Addressed feedback.

**Comment by alex** [comment]
Ugh, looks like our CI is temporarily broken due to https://github.com/PyCQA/flake8-import-order/issues/79, so that's what's causing the failures.

**Comment by alex** [comment]
Jenkins, retest this please.

**Pull request merged**
