### PR TITLE
Comply with PEP 508 by using platform_python_implementation

### PR DESCRIPTION
**Pull request by seppeljordan**

### CODE REVIEW

**Comment by seppeljordan** [comment]
I will close this in a week, if no one takes care of this.

**Comment by alex** [comment]
No need to close this. Both of pyca/cryptography's current maintainers are currently somewhat burned out on it, so we're signifantly slower to respond (and OpenSSL broke our tests so we can't straightforwardly merge things)

**Comment by seppeljordan** [comment]
@alex Okay. Is there anything a regular user could do to help?

**Comment by alex** [comment]
@seppeljordan Can you rebase/merge master please?

Also does this change the supported versions of pip/setuptools?

**Pull request merged**
