### PR TITLE
Add test case for certmonger CSR issue

### PR DESCRIPTION
**Pull request by tiran**
Certmonger used to generate FreeIPA server CSRs with invalid DER.
The CSR encodes a critical=FALSE component in X509v3 extensions although
FALSE is a default value. DER encoding requires that any component value
equal to default is not included.

See: https://github.com/pyca/cryptography/issues/6368
See: https://pagure.io/certmonger/issue/223
See: https://pagure.io/freeipa/issue/9005
Signed-off-by: Christian Heimes <christian@python.org>

### CODE REVIEW

**Comment by tiran** [comment]
The test cases passes with 3.4.8 and fails with 35.0.0.

**Comment by alex** [comment]
Ok, I've taken a provisional look at this, and I have a few questions/comments:

- Does RHEL plan to backport the certmonger fix to current releases so that broken CSRs leave the ecosystem in a timely fashion?
- If we do this, we're going to want to do it on a temporary basis, how long would you want us to maintain this behavior for?
- This PR, as written, changes the `Extension` struct that's also used by certificates, CRLs, OCSP, etc. We do not want to change the behavior for those, we're only willing to consider changing it for CSRs. Can you show what it'd look like to change just CSRs?

**Comment by tiran** [comment]
> I think you'll need something like a `CsrExtension` struct which has the alternate definition.

The struct was the easy part. I'm struggling with Rust's trait system. I cannot figure out how to write a From/Into trait that converts from a sequence of CsrExtensions to a sequence of Extensions.

**Comment by reaperhulk** [comment]
We're getting close-ish to 36.0. What are we planning to do here?

**Comment by tiran** [comment]
> We're getting close-ish to 36.0. What are we planning to do here?

Alex wants the workaround only for CSR parsing. My Rust-fu is not strong enough yet to develop a fix on my own. I tried and failed to implement a trait that converts from CsrExtension to general extension.

**Pull request closed without merging**
