### PR TITLE
Do not use mutable argument defaults

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
[Python Mutable Defaults Are The Source of All Evil](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil)

### CODE REVIEW

**Comment by alex** [comment]
a) Mono-causality is, in fact, the root of all evil.
b) All the objects in question here are immutable, these various list attributes are never mutated. Therefore this PR does not improve safety.

As a result, thank you for the contribution, but we're not going to merge this.

**Comment by DimitriPapadopoulos** [comment]
If they're immutable, how about using tuples instead of lists?

**Comment by alex** [comment]
tuples and lists are not semantically the same: tuples are fixed-length heterogeneous containers, lists are arbitrary length homogeneous containers. using tuples would be semantically wrong.

**Comment by DimitriPapadopoulos** [comment]
immutable ≠ not mutated

**Comment by DimitriPapadopoulos** [comment]
> [...] these various list attributes are never mutated.

If they are not mutated, they could changed into tuples couldn't they?

**Comment by DimitriPapadopoulos** [comment]
Then reopen a new PR? I think you misunderstand what this was about.

**Comment by alex** [comment]
No. We are not accepting this PR. Please stop bothering us about it.

**Pull request closed without merging**
