### PR TITLE
fixes #11453 -- include localKeyID when serializaing a key with a cert

### LINKED ISSUE #11453: Incorrect PKCS12 serialization with version 43
Upgrading from 42.0.8 to 43.0.0, we noticed a change (regression ?) when serializing pkcs12 container.

We use something like

```
    def to_pkcs12(self, password: bytes = b''):
        encryption = PrivateFormat.PKCS12.encryption_builder() \
            .kdf_rounds(50000) \
            .key_cert_algorithm(pkcs12.PBES.PBESv1SHA1And3KeyTripleDESCBC) \
            .hmac_hash(hashes.SHA1()).build(password) if password else NoEncryption()
        return pkcs12.serialize_key_and_certificates(None, self.private_key, self.x509cert, None, encryption)
```

When calling

` openssl pkcs12 -info -nocerts -in cert.p12`

after exporting pkcs12 certificate, we can see that Bag Attribute is empty:

```
AC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 50000
Certificate bag
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 50000
Bag Attributes: <No Attributes>
Key Attributes: <No Attributes>
```

Exact same code running 42.0.8 will have:

```
-----END CERTIFICATE-----
Bag Attributes
    localKeyID: CC E2 4E 5D FC 51 88 11 28 11 AB 52 F5 06 C7 87 E2 82 7A 08
Key Attributes: <No Attributes>
```

Trying to install the certificate (using profile) on an iPad will fail due to missing certificate.

Python 3.12.4
cffi 1.17.0

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Review by reaperhulk — APPROVED** [review]

**Comment by mymy47** [comment]
Hi,
Could you please provide an update on when this commit PR is scheduled for release?

**Comment by alex** [comment]
We don't currently have a plan for our next release. If I had to guess, I'd say early October, but that's a guess.

**Comment by mymy47** [comment]
thanks
is there any way for me to use this commit (localKeyId in pkcs)

**Comment by alex** [comment]
You can depend on cryptography from git (`pip install
git+https://github.com/pyca/cryptography.git`). Note that you'll need
to have our build dependencies installed.

On Sat, Sep 7, 2024 at 8:51 AM mymy47 ***@***.***> wrote:
>
> thanks
> is there any way for me to use this commit (localKeyId in pkcs)
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Pull request merged**
