### PR TITLE
actions: generalize the wycheproof fetch action

### PR DESCRIPTION
**Pull request by woodruffw**
Not hooked up to anything yet. I'll do the actual hookup as part of #8873, since I won't be able to get coverage without it.

### CODE REVIEW

**Comment by woodruffw** [comment]
CI failure looks like a flake.

**Review by alex — COMMENTED** [review]
Instead of a new action can you generalize the wycheproof one

**Comment by woodruffw** [comment]
> Instead of a new action can you generalize the wycheproof one

Done and renamed to `fetch-vectors`.

**Review by alex — COMMENTED** [review]
You'll need to update .github/dependabot.yml as well

**Review by alex — APPROVED** [review]

**Pull request merged**
