### PR TITLE
It's 2016

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
It looks like the test failure in jenkins is because tox isn't properly handling the unicode ellipsis (…) you put in your commit msg. The tox on that builder is 2.3.1 (which is the latest)

**Comment by alex** [comment]
@reaperhulk why does tox even know about the commit message?

**Comment by alex** [comment]
jenkins, retest this please

**Comment by alex** [comment]
Bleh. The ellipsis seems to have fucked up jenkins. Closing and opening a new PR.

**Pull request closed without merging**
