### PR TITLE
Fixed #3422 -- Remove some legacy code which is now in 1.0.1

### LINKED ISSUE #3422: investigate if we still need _ec_key_set_public_key_affine_coordinates
The docs on that method in the openssl backend claim it's a port of a function added in 1.0.1. We only support 1.0.1+ so we might be able to stop using it.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
coverage result looks like nonsense?

**Comment by reaperhulk** [comment]
😢 codecov what's your deal

**Comment by reaperhulk** [comment]
Jenkins, retest this please

**Comment by reaperhulk** [comment]
LGTM, hooray deleting code.

**Pull request merged**
