### PR TITLE
remove deprecated methods

### PR DESCRIPTION
**Pull request by reaperhulk**
We forgot to do this when we started the twelfth release.

### CODE REVIEW

**Comment by alex** [comment]
I think we were intentionally extending the deprecation period of these to _arbitrary future point_?

**Comment by reaperhulk** [comment]
Hmm, I vaguely recall that now. I'll update the PR to just add a comment stating that we have no official timeline for removal of the DeprecatedIn10 functions.

**Comment by reaperhulk** [comment]
Or I'll just put that in the other PR that adds some new deprecation since it's just a single comment.

**Comment by alex** [comment]
Sounds good, you can also remove the usage of DeprecatedIn10 to just DeprecationWarning if you like?

**Pull request closed without merging**
