### PR TITLE
verification: forbid unsupported NCs

### PR DESCRIPTION
**Pull request by woodruffw**
...rather than silently ignoring them.

Needs coverage, which I'll add with https://github.com/C2SP/x509-limbo/pull/228 once I merge that.

### CODE REVIEW

**Comment by alex** [comment]
Do we only want to reject matching pairs, or reject all validations with an other name constraint?

**Comment by woodruffw** [comment]
> Do we only want to reject matching pairs, or reject all validations with an other name constraint?

I _think_ just matching pairs: RFC 5280 says that NCs only need to be evaluated if a subject of the name form appears, so rejecting any cert that has an OtherName NC could (in practice, unlikely) prematurely exclude certs/chains that don't actually have any OtherName SANs.

**Comment by woodruffw** [comment]
I suppose that means I should add a testcase for "validator doesn't reject chain with an OtherName constraint when there's no OtherName SANs" 🙂

**Comment by alex** [comment]
Ok, makes sense, and yeah always test cases are good.

**Comment by woodruffw** [comment]
Merged both new testcases and the CI is green, so this should be good to go 🙂

**Review by alex — APPROVED** [review]

**Pull request merged**
