### PR TITLE
Adding CAVP vector parsing for NIST SP 800-108 KDF vectors.

### PR DESCRIPTION
**Pull request by jared-mess**
Prerequisite for pull request https://github.com/pyca/cryptography/pull/2748

### CODE REVIEW

**Comment by reaperhulk** [comment]
jenkins, ok to test

**Comment by reaperhulk** [comment]
I'd like to see this test output two hashes to demonstrate that it properly recognizes when the next test vector starts. Otherwise LGTM.

**Comment by jared-mess** [comment]
Thank you again reaperhulk for the review, I amended another hash test vector.

**Comment by reaperhulk** [comment]
Thanks @jared-mess, LGTM. Merging now so you can rebase your original PR!

**Pull request merged**
