### PR TITLE
Removed the fastpath from binding initialization. These aren't instantiated frequently enough for this to be worth it, and it improves our coverage.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Not sure what's up with coverage.

**Comment by reaperhulk** [comment]
I restarted an 0.9.8k job in Travis and now coverage properly shows 99.86% (https://codecov.io/github/pyca/cryptography?ref=8db03a1a5389b69ebde678b8b3b35759248a3208). Status API didn't update though.

**Comment by alex** [comment]
@stevepeak ^ Any idea what's going on?

**Comment by stevepeak** [comment]
Hey @alex @reaperhulk doing a lot of maintenance and deploys today. I've seen this issue and working on getting everything back and running smoothly. Thanks!

**Comment by alex** [comment]
Thanks!

On Sun, Jul 12, 2015 at 1:31 PM, Steve Peak <notifications@github.com>
wrote:

> Hey @alex <https://github.com/alex> @reaperhulk
> <https://github.com/reaperhulk> doing a lot of maintenance and deploys
> today. I've seen this issue and working on getting everything back and
> running smoothly. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2139#issuecomment-120753161>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Pull request merged**
