### PR TITLE
add shebang for setup.py scripts

### PR DESCRIPTION
**Pull request by ddcc**
Minor patch to add a shebang to the `setup.py` scripts, this seems to be done by other packages such as `Twisted` and `setuptools`.

### CODE REVIEW

**Comment by reaperhulk** [comment]
I'm assuming these exist for the weird edge case of someone marking `setup.py` as executable and then wanting to run `setup.py {install,test,build_ext,whatever}` without typing "python". /cc @dstufft to confirm that there's not some bizarre reason this is actually needed.

**Comment by ddcc** [comment]
Yes, that's how I encountered it in the first place, although from an external non-UNIX filesystem that applies a +x mask to all files.

**Comment by dstufft** [comment]
It's not really needed except for people who want to execute it directly.

**Comment by reaperhulk** [comment]
I guess I don't see any real problem with adding this, but could you explain a bit more about the system you encountered that expected this behavior @ddcc? Might be useful to know about it for future reference

**Comment by ddcc** [comment]
@reaperhulk It's a bit of a weird setup, but it was from inside a VMWare virtual machine accessing a shared folder on the host NTFS filesystem. Since the host doesn't support UNIX permissions, I believe the default behavior is to apply an executable mask to all files.

Aside from that, I forgot to prepend `python` to `setup.py` when attempting to run the tests.

**Comment by alex** [comment]
Jenkins, ok to test.

**Pull request merged**
