### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by jcea**

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test

**Comment by alex** [comment]
(FYI tests aren't going to pass until #2755 is landed, but this looks great, thanks!)

**Comment by alex** [comment]
So, these are all doctests, which means that variable needs to be defined. You can add it at the top of the file next to where the pem values are defined.

**Comment by reaperhulk** [comment]
Bump: are you still interested in completing this PR? If you don't have time we can take over and finish it.

**Comment by reaperhulk** [comment]
Closing due to lack of activity. We can reopen if you'd like to update!

**Comment by alex** [comment]
We still need to fix this, is there an open issue?

On Wed, Apr 13, 2016 at 10:40 AM, Paul Kehrer <notifications@github.com>
wrote:

> Closing due to lack of activity. We can reopen if you'd like to update!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2756#issuecomment-209478821>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by reaperhulk** [comment]
Nope, we should file one.

**Pull request closed without merging**
