### PR TITLE
fix a regression in int_from_bytes

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
test please

**Comment by ofek** [comment]
Py2 doesn't have built-in `bytes`.

**Comment by alex** [comment]
The name `bytes` exists on py2 just fine.

**Comment by ofek** [comment]
Huh ty, TIL. [https://docs.python.org/3/whatsnew/2.6.html#pep-3112-byte-literals](url)

**Comment by ofek** [comment]
Hey quick question wrt terminology, as I'm unfamiliar with this.

Generally, are internal utilities considered part of the public API? If not, is this actually classified as a regression? Looking at the offending line [https://github.com/mitya57/secretstorage/blob/master/secretstorage/dhcrypto.py#L36](url) it seems a bytearray is being passed to our int_from_bytes.

Cryptography doesn't use bytearrays at all atm (eventually maybe #3119)

**Comment by alex** [comment]
Technically no, the public API is defined by what is documented. That said, we know we have a lot of downstream users, so we try to avoid breaking them (particularly unintentionally!)

**Pull request merged**
