### PR TITLE
Split out asymmetric key interfaces

### PR DESCRIPTION
**Pull request by greghaynes**
Splitting out RSA, DSA, and EllipticalCurve interfaces as part of #1495.

### CODE REVIEW

**Comment by alex** [comment]
ok to test

**Comment by alex** [comment]
add to whitelist

**Comment by public** [comment]
RSA is already being done in #1592. Can you do DSA and EC in their own PRs and properly deprecate the old names like is done in that PR?

**Comment by greghaynes** [comment]
retest this please

**Comment by reaperhulk** [comment]
I'm not sure why we haven't merged this yet. Anybody have a reason or did it just slip through the cracks? Will merge tomorrow if no one objects.

**Comment by alex** [comment]
@reaperhulk I haven't reviewed at all, but conceptually looks ok to me (will cause some merge conflicts on @public's PR :-)); I'll leave it to you to review/merge.

**Comment by greghaynes** [comment]
I tried to remove the RSA bits once I saw Public's patch to try and help with the merge conflicts... Even so, I wont be terribly offended if we think this is going to be outdated fast enough by public's work that it shouldnt merge :)

**Comment by alex** [comment]
I'm perfectly happy to take incremental progress, the rebase shouldn't be
too bad, and this is a clear improvement.

**Pull request merged**
