### PR TITLE
try `EVP_CIPHER_fetch` due to `EVP_get_cipherbyname` is deprecated

### PR DESCRIPTION
**Pull request by boyxuper**
see: https://www.openssl.org/docs/manmaster/man3/EVP_EncryptInit.html#EVP_get_cipherbyname-EVP_get_cipherbynid-and-EVP_get_cipherbyobj
see: https://github.com/openssl/openssl/issues/13667#issuecomment-1034505341

use case:
obtain sm4-gcm / sm4-ccm with OpenSSL 3.1.0 (master branch)

### CODE REVIEW

**Comment by alex** [comment]
We require test vectors for any new algorithm.

It looks like sm4-gcm isn't present until 3.1, therefore this will have to wait until then.

**Comment by boyxuper** [comment]
It's just cipher-getter, not related to specific algorithm, And sm4-gcm test vector added.

**Comment by boyxuper** [comment]
@alex  Can I separate sm4-gcm part to another PR, and just take the first commit ?

**Comment by reaperhulk** [comment]
@boyxuper yes we'd be willing to review a PR that just modifies the fetch path to use the newer method.

**Comment by boyxuper** [comment]
> @boyxuper yes we'd be willing to review a PR that just modifies the fetch path to use the newer method.

@reaperhulk  I just dropped other commits.

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
