### PR TITLE
add SSL_CTX_(get|set)_keylog_callback

### PR DESCRIPTION
**Pull request by mhils**
Replacement for #5179. :smiley:

### CODE REVIEW

**Comment by rugk** [comment]
https://github.com/pyca/pyopenssl/pull/910 depends on this. So could a release with this feature be made?

**Comment by reaperhulk** [comment]
We're tentatively planning a release in the next week or so.

**Comment by rugk** [comment]
I'm not here to rush you (we are two weeks later now), but pyca/pyopenssl#910 depends on this, which https://github.com/mitmproxy/mitmproxy/issues/3994 depends on.

**Comment by reaperhulk** [comment]
cryptography 3.0 was released over a week ago. It looks like mhils just rebased the pyopenssl PR today though.

**Pull request merged**
