### PR TITLE
Run tests on buster

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Is there any real difference between sid and buster for the next year or so?

**Comment by alex** [comment]
No clue

**Comment by reaperhulk** [comment]
cc @mithrandi 😁

**Comment by mithrandi** [comment]
Since packages do not migrate from sid to buster instantly, there will be transient differences, but I don't think there is any need to test against both. Probably you only need to worry about sid until buster enters freeze at the end of the release cycle.

**Comment by alex** [comment]
My personal attitude is that we may as well do it now, and not worry about it in the future. It doesn't add much time to CI.

**Comment by reaperhulk** [comment]
I'm opposed mostly because we don't have the parallel capacity to do all our docker builds simultaneously at this point. I wouldn't care if we had a secondary docker builder, but we haven't decided to do that yet ;)

**Comment by reaperhulk** [comment]
(We have more docker capacity now)

**Pull request merged**
