### PR TITLE
Don't internal error on CRL with no nextUpdate value

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Does this have a valid or invalid sig? If invalid please note that in the docs

**Comment by alex** [comment]
done

**Review by reaperhulk — APPROVED** [review]

**Comment by reaperhulk** [comment]
We should add a changelog entry stating that next update is now correctly parsed as optional.

**Comment by alex** [comment]
Do we normally note bug fixes in teh changelog?

**Comment by reaperhulk** [comment]
We're not consistent, so we could go either way. I'm good with it being in a separate PR though if we decide to do it.

**Pull request merged**
