### PR TITLE
Refs #3405 -- use ASAN/UBSAN when compiling on travis

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
I guess we'll see what versions of clang/gcc have this...

**Comment by alex** [comment]
@reaperhulk That was my theory!

**Comment by alex** [comment]
So, the precise builders do not have it.

**Comment by reaperhulk** [comment]
What if we did this in Jenkins instead now that we have Jenkinsfile?

**Comment by alex** [comment]
Doing this in Jenkins is a reasonable idea.

**Comment by alex** [comment]
Closing this out since this patch is not working and I haven't been making time for it.

**Pull request closed without merging**
