### PR TITLE
Enforce text type of NameAttribute.value

### PR DESCRIPTION
**Pull request by sigmavirus24**

### CODE REVIEW

**Comment by reaperhulk** [comment]
This is going to fail in py2 tests as quite a few tests are failing to initialize using unicode values. We'll need to update the tests.

**Comment by reaperhulk** [comment]
jenkins, add to whitelist

**Comment by alex** [comment]
@sigmavirus24 can you add a changelog entry for this

**Comment by sigmavirus24** [comment]
Changelog updated.

**Pull request merged**
