### PR TITLE
Testing codecov/support#43

### PR DESCRIPTION
**Pull request by stevepeak**
Read more at https://github.com/codecov/support/issues/43 Thanks!

### CODE REVIEW

**Comment by alex** [comment]
Hmm, the number in this comment looks wrong, some of the individual builds have a higher coverage than that, is it not aggregating?

**Comment by stevepeak** [comment]
I wonder if `coverage4.0a6` is collecting the right data

```
==> Coverage cli exists, replacing with https://bitbucket.org/codecov/coverage.py, replacing with https://bitbucket.org/codecov/coverage.py
Uninstalling coverage-3.7.1:
  Successfully uninstalled coverage-3.7.1
Collecting https://bitbucket.org/codecov/coverage.py/get/9b848b6.tar.gz
  Downloading https://bitbucket.org/codecov/coverage.py/get/9b848b6.tar.gz (429kB)
Installing collected packages: coverage
  Running setup.py install for coverage
Successfully installed coverage-4.0a6
```

- First issue I found was in the new conditions internally which I'm patching an rebuilding

**Comment by alex** [comment]
It looks like you install the new coverage after tests have already been
run. Is that too late?

On Sat, Jun 27, 2015 at 8:06 AM, Steve Peak <notifications@github.com>
wrote:

> I wonder if coverage4.0a6 is collecting the right data
>
> ==> Coverage cli exists, replacing with https://bitbucket.org/codecov/coverage.py, replacing with https://bitbucket.org/codecov/coverage.py
> Uninstalling coverage-3.7.1:
>   Successfully uninstalled coverage-3.7.1
> Collecting https://bitbucket.org/codecov/coverage.py/get/9b848b6.tar.gz
>   Downloading https://bitbucket.org/codecov/coverage.py/get/9b848b6.tar.gz (429kB)
> Installing collected packages: coverage
>   Running setup.py install for coverage
> Successfully installed coverage-4.0a6
>
>
>    - First issue I found was in the new conditions internally which I'm
>    patching an rebuilding
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2070#issuecomment-116024457>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by stevepeak** [comment]
@alex I'm using it to run `coverage xml` which (as far as I can tell) should work because the raw coverage data is found in `.coverage`. The new `coverage xml` should use the `.coverage` file to produce the xml and add the `<conditions>` accordingly. Its a little gamble, but should pay off.

**Comment by alex** [comment]
Ah, makes sense.

On Sat, Jun 27, 2015 at 9:13 AM, Steve Peak <notifications@github.com>
wrote:

> @alex <https://github.com/alex> I'm using it to run coverage xml which
> (as far as I can tell) should work because the raw coverage data is found
> in .coverage. The new coverage xml should use the .coverage file to
> produce the xml and add the <conditions> accordingly. Its a little
> gamble, but should pay off.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2070#issuecomment-116044770>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by stevepeak** [comment]
Sorry about the multiple comments. Its a glitch when no coverage is on master. Fixing now. :shipit:

**Comment by alex** [comment]
Cool. The results are looking correct; I guess we need to fix our branch coverage before we can merge this? /cc @reaperhulk

**Comment by stevepeak** [comment]
Yea, progress is in the air! I'm glad this is working. I'm slightly worried about that version of `coveragepy` I'm going to fork a stable version and add the `<conditions>`.

**Comment by reaperhulk** [comment]
Looks like there's an issue where all the test files are 404 if you try to view them (https://codecov.io/github/pyca/cryptography/tests?ref=93baf9dfc0f128d70f9dae0fad74ae21d249ff37)

**Comment by reaperhulk** [comment]
Actually I'm 404ing on everything so there must be some other issue (as this was working for me a few minutes ago)

**Comment by alex** [comment]
@reaperhulk looks ok to me, can you confirm if this is still an issue?

**Comment by reaperhulk** [comment]
Yep, every file 404s when I try to view the coverage.

**Comment by stevepeak** [comment]
Not sure whats going on.... with `93baf9dfc0f128d70f9dae0fad74ae21d249ff37`

- [Commit exists][1] :heavy_check_mark: 
- [Github 500's when lookup file][2] :x: 
- Github API for that file :x: 
```
curl https://api.github.com/repos/pyca/cryptography/contents/tests/conftest.py\?ref\=93baf9dfc0f128d70f9dae0fad74ae21d249ff37
```


[1]: https://github.com/pyca/cryptography/commit/93baf9dfc0f128d70f9dae0fad74ae21d249ff37
[2]: https://github.com/pyca/cryptography/blob/93baf9dfc0f128d70f9dae0fad74ae21d249ff37/tests/conftest.py

**Comment by alex** [comment]
Oof. Not sure what to make of that error. It seems like maybe it's a github API bug?

**Comment by stevepeak** [comment]
> First 500 error I've seen on Github. I feel like I won something... :balloon: :cake: 

Hum..I'll try another build.

**Comment by alex** [comment]
Ok, it looks like besides the part where we need to fix our branch coverage, this is fully functional!

**Comment by reaperhulk** [comment]
@alex what do you think about opening this as a new PR and then setting our minimum required to exactly the percentage we get back from codecov? Then we can have this info on every PR and get up to 100% ASAP.

**Comment by alex** [comment]
Seems good, we'll have to make sure to continually bump it whenever we
improve it, so nothing regresses.

On Sun, Jun 28, 2015 at 6:21 PM, Paul Kehrer <notifications@github.com>
wrote:

> @alex <https://github.com/alex> what do you think about opening this as a
> new PR and then setting our minimum required to exactly the percentage we
> get back from codecov? Then we can have this info on every PR and get up to
> 100% ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2070#issuecomment-116355692>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
Closing in favor of #2089, thanks!

**Pull request closed without merging**
