### PR TITLE
Attempt to use coverage to quantify how many of the CONDITIONAL_NAMES we really use

### PR DESCRIPTION
**Pull request by alex**
The last time I sent this, we used it just as a temporary run. Now I want to propose we really use it :-)

### CODE REVIEW

**Comment by alex** [comment]
@reaperhulk `Cryptography_HAS_DTLS` and `Cryptography_HAS_EC2M` are apparently unused in CI. Objections to removing them?

**Comment by reaperhulk** [comment]
According to the changelog `no-ec2m` was only added in 1.1.0 so it seems unlikely that anybody actually uses it (why is it even an option...). No DTLS might be somewhere, but I guess the only way we're going to learn about it is to drop support and see what happens. So, 👍 on removing both.

**Comment by alex** [comment]
I'll do seperate PRs 👍

**Comment by alex** [comment]
So, for whatever reason, codecov is not finding a coverage report on the CentOS7 builder, leading to this issue. wat.

@reaperhulk any clue why it fails?

**Comment by reaperhulk** [comment]
Well that's bizarre. No idea what's going on. I guess we can pull down the image and run it ourselves to see what happens though.

**Pull request merged**
