### PR TITLE
More accurate LibreSSL detection

### PR DESCRIPTION
**Pull request by moriyoshi**
This fixes builds on LibreSSL >= 2.5.3

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by reaperhulk** [comment]
Jenkins, retest this please.

**Comment by reaperhulk** [comment]
Jenkins, retest this please

**Comment by moriyoshi** [comment]
Is there anything I can do to get this merged?

**Comment by reaperhulk** [comment]
The issue I have with the current fix is that it will break again with LibreSSL 2.5.5+ unless these constants are added by the LibreSSL project. This probably needs to be `#ifndef` or `#if !defined()` for each constant (along with a comment lamenting LibreSSL's decisions so we remember why there are separate ifndefs)

**Comment by hasufell** [comment]
Why did this not land in `v1.8.2`? The commits cannot be cherry-picked properly.

**Comment by reaperhulk** [comment]
Because we also needed #3609 and the 1.8.2 release was scoped to fix a 1.1.0f breakage. We'll be releasing 1.9 with the libre fixes early next week.

**Pull request merged**
