### PR TITLE
revert a change to our exceptions for asymmetric key loading

### PR DESCRIPTION
**Pull request by reaperhulk**
Previously when bad data was passed we'd raise ValuError. In the DH PR (#3369) we modified it so under some scenarios (that were too broad) it would raise UnsupportedAlgorithm. Since this was unnecessary this PR reverts it.

### CODE REVIEW

**Comment by alex** [comment]
Conceptually this looks ok, but still a handful of failing tests.

**Comment by alex** [comment]
Still failing on some builders.

**Comment by reaperhulk** [comment]
The current failure is because on OpenSSL < 1.0.2 trying to load a DER encoded DH X9.42 key raises a generic error, while the PEM path raises an error that we have previously defined to raise UnsupportedAlgorithm. Trying to make both PEM and DER return the same error here will be difficult, as we need to preserve the existing exception behaviors for key loading.

If we want to continue using the existing key loading and error handling paths then we're going to be stuck with raising ValueError for PEM/DER public keys and DER private, but UnsupportedAlgorithm for PEM private. Is this acceptable or should we create a new key loading & error handling path just for these DHX keys?

**Comment by alex** [comment]
Jenkins, retest this please.

**Comment by reaperhulk** [comment]
Jenkins, retest this please

**Comment by palaviv** [comment]
Sorry for the late comment. I would like to suggest a different approach for the problem:
1. Change `UnsupportedAlgorithm` to inherit from `ValueError`
2. Create new exception that inherit from both  `UnsupportedAlgorithm` and `ValueError`.

**Pull request merged**
