### PR TITLE
Run our vector verification go program

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
I suspect this is going to take a few tries to get everything happy on travis

**Comment by Ayrx** [comment]
This would mean that golang is now a requirement for development? We should add that to the docs then.

**Comment by alex** [comment]
I think travis is configured right, but this is blocked on #1617

**Comment by reaperhulk** [comment]
This seems like a better candidate for a jenkins job than travis to me (since it doesn't affect coverage)

**Comment by Ayrx** [comment]
Jenkins job sounds good.

**Comment by alex** [comment]
@reaperhulk So, if we run this under jenkins, do you still want it in the `tox.ini`?

(It's slightly awkward there, `tox` really wants what you run to be a Python program)

**Comment by reaperhulk** [comment]
I'd be okay with it not being in tox if the tox invocation is weird (which makes sense)

**Comment by alex** [comment]
You can see what it looks like; note that if you run it you get some
warnings because the `go` binary lives outside of the virtualenv; I can't
find a way to make it go away.

**Comment by public** [comment]
I also think it would be better if this was not done in Tox.

**Comment by alex** [comment]
Ok, I'm going to close this then.

**Pull request closed without merging**
