### PR TITLE
Have CertificateBuilder docs create self-signed cert

### PR DESCRIPTION
**Pull request by Lukasa**
This resolves some of the difficulties people have bumped into with this recipe.

### CODE REVIEW

**Comment by alex** [comment]
lgtm

**Comment by reaperhulk** [comment]
The failing tests might be related to the release of pytest 2.8.4 (I am really getting tired of all our deps breaking our CI :crying_cat_face: )

**Comment by alex** [comment]
Looks like it. Can someone file a bug with upstream and send a separate PR to pin in the mean time?

**Comment by sigmavirus24** [comment]
Sans failing tests, :+1: from me.

**Comment by alex** [comment]
According to @sigmavirus24 the following shenangins will make travis re-test.

**Comment by sigmavirus24** [comment]
Good thing little hacks like that exist, right?

**Pull request merged**
