### PR TITLE
Make some random bash changes to appease shellcheck.

### PR DESCRIPTION
**Pull request by alex**
I don't understand its ways, but it seemed smart.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Seems reasonable.

**Comment by alex** [comment]
DOES IT?

**Comment by reaperhulk** [comment]
Well `otool -L "$(find .tox -name '_openssl*.so')"` doesn't appear to actually work on my computer, but other than that :)

**Comment by alex** [comment]
Sigh.

On Thu, Sep 10, 2015 at 7:00 PM, Paul Kehrer <notifications@github.com>
wrote:

> Well otool -L "$(find .tox -name '_openssl*.so')" doesn't appear to
> actually work on my computer, but other than that :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2335#issuecomment-139406076>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
I'm going to can this PR. Should have tested it properly first, not worth the effort.

**Pull request closed without merging**
