### PR TITLE
Prefer travis_retry instead of bash shenangins.

### PR DESCRIPTION
**Pull request by alex**
This has a few advantages:

- reduces duplication which decreases changes of typos and makes sure we actually covera ll the line
- consistent number of retries
- better output on retries

### CODE REVIEW

**Comment by alex** [comment]
Eh, shit. Bash functions don't survive new invocations of the shell (which should have been obvious, but lol). We can either

- a) `source` the scripts instead of running them
- b) ignore this PR

@reaperhulk preference?

**Comment by reaperhulk** [comment]
Sourcing the scripts to gain the helper functions seems reasonable to me. I guess if we want to do that we should put a comment explaining why we source rather than invoking directly though.

**Comment by alex** [comment]
I don't understand why this makes 2.6 fail. @reaperhulk do you?

**Comment by alex** [comment]
not worth it

**Pull request closed without merging**
