### PR TITLE
Remove unused X509 verification flags bindings

### PR DESCRIPTION
**Pull request by davidben**
These don't appear to be used in pyopenssl or cryptography.io. One less source of conditionals.

### CODE REVIEW

**Review by alex — APPROVED** [review]
Will leave this open until @reaperhulk double checks me on if there's a user

**Review by alex — DISMISSED** [review]
Ooops, these need to eb removed from the other place they're present in that file, around L103 or so.

**Comment by davidben** [comment]
Oops, not sure how I missed that. Rebase mishap, maybe. Fixed, hopefully.

**Comment by reaperhulk** [comment]
pyOpenSSL definitely never used these so I'm comfortable with removing them.

**Review by reaperhulk — APPROVED** [review]

**Comment by reaperhulk** [comment]
To be clear I'm unaware of any consumers of this, but I'm very sure pyOpenSSL has never used these flags since I checked the entire git history.

**Pull request merged**
