### PR TITLE
Make X509_ALGOR opaque

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
😱 looks like we need to do work on the pyopenssl side for this

**Comment by alex** [comment]
https://github.com/pyca/cryptography/pull/9739

**Review by reaperhulk — APPROVED** [review]

**Comment by botovq** [comment]
That's a nice surprise. Thanks, @alex

**Comment by alex** [comment]
If it's relevant: I've backported the new binding to our 41.x branch, which will get a release next week (for the OpenSSL sec release). After that we'll merge the pyOpenSL PR and do a release, and after that we can merge this.

And then I will take a nap.

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
