### PR TITLE
Run tests on aarch64, ppc, and s390x

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Failures seem to be caused by caching here: https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822

**Comment by alex** [comment]
This uses distro OpenSSL (1.0.2). Do we want to build our own here? In addition to or instead of the distro?

**Comment by reaperhulk** [comment]
We should probably do both at least on aarch64 since we're likely to ship a wheel there. I don't much care about ppc64le or s390x but I guess they can stay?

**Comment by alex** [comment]
Ok, added a 1.1.1f build for aarch64, left ppc and s390x as is.

**Pull request merged**
