### PR TITLE
Adding new exported functions

### PR DESCRIPTION
**Pull request by thierryba**
I'm using the backend directly to create for instance DHparams files. I needed to patch cryptography this way to have access to those functions. I hope to one day have a high level API for it. In the meantime, I would love if you could consider adding those functions. I'm seeing that other ones are there and are also useful.

Thanks for a great library!

### CODE REVIEW

**Comment by palaviv** [comment]
Hi @thierryba would something like what I wrote in #3408 be helpful for you as high level API?

**Comment by thierryba** [comment]
@palaviv: yes that would help.

**Comment by reaperhulk** [comment]
To merge this (and #3408 will probably need these anyway) we'll need to do conditional bindings so that compilation doesn't fail on OpenSSL versions without DHX. We have some [docs](https://cryptography.io/en/latest/development/c-bindings/) on how to do this and you can also look in the existing bindings to find examples.

**Comment by thierryba** [comment]
I'm not super familiar with openssl and it macros but I can see this in pem.h (openssl 1.0.2, which is the minimum you guys support)

# ifndef OPENSSL_NO_DH
DECLARE_PEM_rw_const(DHparams, DH)
DECLARE_PEM_write_const(DHxparams, DH)
# endif

so it looks like Dhxparams is present if DHparams is. Or am I missing something?

**Comment by reaperhulk** [comment]
We support 1.0.1 :)

**Comment by alex** [comment]
Jenkins, ok to test

**Comment by reaperhulk** [comment]
#3485 adds one of the two bindings here. If you still need the other one would you mind opening another PR? It'd be very helpful to explain the utility of that dup function as well.

**Pull request closed without merging**
