### PR TITLE
vectors generated by the custom vector generator in #1867

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
I think this has the wrong base commit or something, the `generate_secp256k1.py` and verify files don't actually exist. Would you mind rebasing so I can verify more conveniently :-)

(Also, what do you think about having the verify scripts run on CI?)

**Comment by public** [comment]
The scripts were in #1867 which is now merged.

**Comment by reaperhulk** [comment]
@alex was asking for me to rebase it so they'd appear in this specific PR without the merge commit I think. I have done that now :)

**Comment by public** [comment]
Given that I wrote the scripts I think I'll leave it for someone else to check the vectors :)

**Comment by eeshangarg** [comment]
Hi! I generated the vectors using ```generate_secp256k1.py``` and verified them using the verification script ```verify_secp256k1.py``` and everything passed. So, it's a +1 from me on merging this. :-)

**Pull request merged**
