### PR TITLE
[WIP] [Question] Add incremental API for `fernet` encryption

### PR DESCRIPTION
**Pull request by alexander255**
I know this is still lacking in several ways, but could somebody from the *corer* development team give feedback on whether this is something that is in line with the project goal?

### CODE REVIEW

**Comment by alex** [comment]
This API involves exposing un-authenticated plaintext to users, and that is not consistent with the safety goals of the recipe layer, so we will not support this functionality.

**Comment by alexander255** [comment]
You mean the fact that `_Decryptor` returns data sets without waiting for the completion of the HMAC validation?

**Comment by alexander255** [comment]
Would it make sense to expose the `Decryptor` in `hazmat` instead?

**Comment by reaperhulk** [comment]
If you're looking for a streaming API with authentication we already support that in the form of the AES GCM construct -- does this not meet your needs? Fernet is meant to be a one shot API specifically to prevent possible misuse of data before the payload is authenticated. This unfortunately makes it unsuitable for encryption of large payloads. We have some vague ideas for having a streaming/seekable encryption format like Fernet using framing, but for now the AES GCM API can give you what you want at the cost of no integrity guarantees until decryption is complete.

**Comment by alexander255** [comment]
@reaperhulk You're right about that. I'm looking a way to efficiently stream large (100MB+) datasets using one-shot symmetrical encryption between clients over an potentially untrusted network of servers. Considering that the data indeed might be processed/disolayed in some way before the download completes, I must admit that trying to stream fernet was a bad idea…
OTOH simply chunking the data into ~10kB packets that are each encrypted separately (using the same key, but different IV) would add about 0.6% overhead without impairing the used crypto in any way, right?

**Comment by reaperhulk** [comment]
Yep, framing in that fashion is fine for what you want, just not what we'd like to do as a generic solution. Of course, I'd be remiss if I didn't say you should really be using TLS if at all possible for network communication.

**Comment by alexander255** [comment]
Ok, thanks for the feedback! One more thing I'm wondering about: Is it safe to just throw an unsigned length field in front of each fernet packet to declare the following packet's total length? Unless I'm missing something obvious (and this thread serves as public documentation that such a thing has happened before) the HMAC should "never" realistically be able to validate if the length was wrong, right?
And yes, I'm very painfully aware about not being to use TLS in this case. :confused:

**Pull request closed without merging**
