### PR TITLE
Use `d` instead of `private_exponent` for consistency

### PR DESCRIPTION
**Pull request by djc**
True story: I used `e` instead of `d` because it seemed more closely related
to `private_exponent`. Should have looked it up, of course... but the docs could be better.

### CODE REVIEW

**Comment by alex** [comment]
Jenkins, ok to test.

**Comment by alex** [comment]
Mmm, this change would be backwards incompatible for anyone using keyword arguments.

**Comment by djc** [comment]
How about this version, instead?

**Comment by alex** [comment]
lgtm, will merge once tests pass

**Pull request merged**
