### PR TITLE
support OpenSSL built with no-comp

### PR DESCRIPTION
**Pull request by reaperhulk**
refs #1622 

This PR should fix building OpenSSL with compression disabled (no-comp) on all platforms. On Windows we (apparently) have to declare the functions before we remove them via `CONDITIONAL_NAMES`. For more information about why see: https://github.com/pyca/cryptography/pull/1622#issuecomment-72643336

### CODE REVIEW

**Comment by reaperhulk** [comment]
@schlenk when you get a chance could you confirm this works for you?

**Comment by alex** [comment]
I don't understand why Windows is special here, and the comment you linked doesn't explain it IMO.

**Comment by schlenk** [comment]
Doesn't compile when OPENSSL_NO_COMP is defined (you missed the parameter names in the lines 569, 572, 575) of ssl.py.

**Comment by schlenk** [comment]
Once those are fixed, it compiles and can be used, tests run. (64-Bit Version, will test 32-Bit at work).

**Comment by alex** [comment]
This needs a rebease.

**Comment by reaperhulk** [comment]
@schlenk Do you happen to have an installer for an OpenSSL with no-comp on Windows? Or, failing that, a simple way to compile OpenSSL on Windows? I've never actually done it :)

**Comment by schlenk** [comment]
@reaperhulk Compiling OpenSSL on Windows is actually easy enough 

Open a cmd shell and run vcvarsall.bat to get the compiler path etc.
```
perl Configure --prefix=d:\code\openssl no-comp no-ssl2 no-ssl3 VC-WIN32
ms\do_ms.bat    (or ms\do_nasm.bat if you have the NASM assembler installed and need the speed)
nmake -f ms\ntdll.mak   (or nmake -f ms\nt.mak if you only want the static libs, the issue might only appear with the dynamic lib, not sure.)
```
there is install target, but the libs are there (but not with the 'mt' suffixes expected by the cryptography build, so just rename the .lib files), see the out32 and inc32 folders.

**Comment by schlenk** [comment]
Ok. Builds now (on Windows x64_64, Python 2.7.9rc1_x64 from python.org, openssl-1.0.2 with no-comp) and tests run without failures.

**Comment by schlenk** [comment]
Ping. Works for me now. Anything I could do to get this one merged?

**Comment by alex** [comment]
So the UNIX bits here look ok to me, but I still don't understand why Windows is special?

**Comment by alex** [comment]
Could we start with a version that just added the `defined(OPENSSL_NO_COMP)` to the thing

**Comment by schlenk** [comment]
Some more information:
The windows build works fine without the extra `#ifdef (_WIN32)` stuff in the patch, if openssl is linked statically. That makes sense, as the broken .def file from openssl which hides the symbols is just used for building the DLL version.
So for static linking, the windows code is 100% identical to the Linux version with OPENSSL_NO_COMP. Only for dynamic linking there is a difference due to the weird way openssl builds but hides those symbols which lets the MS linker complain. In fact, the 'static link' case breaks with the `#ifdef (_WIN32)` part included, while 'dynamic' works.

Not nice. Guess one could remove the #ifdef (_WIN32) block from the patch and at least fix the build for the (probably more common) static linking case. No idea how to get both the static and dynamic version to work easily.

**Comment by alex** [comment]
needs a rebase now.

**Comment by reaperhulk** [comment]
This has been rebased, but if the current approach doesn't work for both dynamic/static I'm very much against it being merged.

**Comment by alex** [comment]
Agreed.

**Comment by schlenk** [comment]
Thx for merging #1824. That at least fixes the problem for the most common cases (including static libssl on Windows). 
Anyone using the .dll version has probably built it anyway, so could they could patch the crappy .def file too, which would make this a non-issue. (and maybe the openssl guys fix the interface for the future).

**Comment by reaperhulk** [comment]
I think I'm going to close this for now. We can reopen if necessary, but hopefully it'll just get fixed upstream.

**Pull request closed without merging**
