### PR TITLE
Add support for GCM mode of SM4 cipher

### PR DESCRIPTION
**Pull request by mnixry**
ref: #7503
ref: https://github.com/openssl/openssl/issues/13667

[RFC8998](https://datatracker.ietf.org/doc/html/rfc8998), SM4-GCM support, has been added into OpenSSL for a year. 
It will be nice if we can add support to this package.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Thanks for the contribution. A few questions/requests:

* Could you format the test vectors as we do for our other SM4 test vectors? (see: https://github.com/pyca/cryptography/blob/main/vectors/cryptography_vectors/ciphers/SM4/draft-ribose-cfrg-sm4-10-cbc.txt). You can name the file `rfc8998.txt` in that directory. Please make sure you also add the information about the vectors to `test-vectors.rst` under the Symmetric Ciphers section.
* I'd like to see some tests for the negative case (`InvalidTag`) as well.
* Is SM4-GCM used outside of this TLS cipher suite? Are Chinese browsers implementing this suite? Understanding the use case is always helpful 😄

**Comment by mnixry** [comment]
Thank you for your suggestions! Tests has been update according to request.

> Is SM4-GCM used outside of this TLS cipher suite? Are Chinese browsers implementing this suite?

Yes. AFAIK SM2/3/4 supported browser (and certificate for hosting website) has been a part of compliance requirement of some highly confidential scenario. 
Some VPN, for accessing internal network, are also adapting SM4-GCM as their encryption approaches.

**Comment by reaperhulk** [comment]
This mostly looks good, but two final requests 😄 

* Could you add a positive and negative test case using `finalize_with_tag`?
* Please add an entry to `CHANGELOG.rst` (something along the lines of "added support for SM4 GCM when using OpenSSL 3.0 or greater")

**Review by reaperhulk — APPROVED** [review]

**Comment by reaperhulk** [comment]
Thanks again!

**Pull request merged**
