### PR TITLE
Update Python 3s & limit pyenv history cloned

### PR DESCRIPTION
**Pull request by hynek**
Use up to date Python 3.4 & 3.5 and `--depth 1` should give us a performance boost!?

### CODE REVIEW

**Comment by alex** [comment]
Looks great, will merge as soon as jenkins is healthy and passing.

**Comment by reaperhulk** [comment]
I'm not sure a shallow clone is of any advantage here. It reduces disk usage but dramatically increases the CPU required to deliver the clone from GitHub (see https://github.com/CocoaPods/CocoaPods/issues/4989), which is likely to raise overall time before the clone is complete.

**Comment by alex** [comment]
Measuring locally it's significantly faster with the depth flag.

**Comment by reaperhulk** [comment]
Locally for me it's 1.6 (standard) vs 1.3s (depth=1). So, marginally faster I guess.

**Comment by alex** [comment]
I was seeing ~3s vs. 0.8s. FWIW my understanding of the cocoapods is that the thing that's slow is specifically doing a `pull` or other `git` operations on a cloned repo, not the `clone --depth=` itsefl

**Comment by alex** [comment]
Jenkins, retest this please.

**Comment by hynek** [comment]
aren’t they complaining about what happens if you do a `--depth=0` and then pull without a limiter on top of it?

**Comment by alex** [comment]
@hynek that was my understanding

**Comment by hynek** [comment]
FWIW:

```
➤ time git clone --depth 1 https://github.com/yyuu/pyenv.git t1
Cloning into 't1'...
remote: Counting objects: 517, done.
remote: Compressing objects: 100% (400/400), done.
remote: Total 517 (delta 197), reused 238 (delta 37), pack-reused 0
Receiving objects: 100% (517/517), 236.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (197/197), done.
        1.59 real         0.06 user         0.09 sys
~/tmp
➤ time git clone https://github.com/yyuu/pyenv.git t2
Cloning into 't2'...
remote: Counting objects: 13707, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 13707 (delta 23), reused 0 (delta 0), pack-reused 13650
Receiving objects: 100% (13707/13707), 2.43 MiB | 2.12 MiB/s, done.
Resolving deltas: 100% (9521/9521), done.
        3.50 real         0.25 user         0.21 sys
```

**Pull request merged**
