### PR TITLE
[DO NOT MERGE] Fixes #3548 - add a pyproject.toml

### LINKED ISSUE #3548: Add PEP 518 pyproject.toml

### PR DESCRIPTION
**Pull request by alex**
Don't merge until PIP X is out.

### CODE REVIEW

**Comment by alex** [comment]
pip x comes out in a week. I'd like to make a radical proposal:

1. We drop `setup_requires` entirely from our `setup.py`; with pip x you'll get cffi installed, if you're on an older `pip` or `setuptools` you can either upgrade to pip x or manually install `cffi`
2. We make `setup.py` error cleanly if you don't have `cffi` installed, telling you about (1)
3. We delete all the wild code for disabling `setup_requires` if the `setup.py` command doesn't need it.

Reasons:

1. Encourage people to upgrade to pip x
2. Working around this is easy, just `pip install cffi>1.7` if you can't upgrade `pip` for any reason
3. Let's us delete tons of obscure code
4. Helps kill off `easy_install` once and for all, thus protecting against scenarios like "using macOS<10.13 with system python and `pip install cryptography` successfully downloads `cryptography`, but then installing it fails to download `cffi` since that download is done by `setuptools`"

**Comment by reaperhulk** [comment]
Top 10 versions (including both pip and setuptools) used to install cryptography 2.2.2 (latest version) since it was released:

image

I'm baffled why 1.5.4 is so enormous. It isn't on any other PyCA project.

**Comment by dstufft** [comment]
https://packages.ubuntu.com/trusty/python-pip

**Comment by alex** [comment]
This is blocked on:

- [ ] https://github.com/msgpack/msgpack-python/issues/299
- [ ] https://github.com/pypa/get-pip/issues/19

**Comment by alex** [comment]
Turns out pip x only supports pyproject.toml with packages distributed as wheels, so we can't use it yet:

https://github.com/pypa/pip/issues/5229

**Comment by alex** [comment]
Closing in favor of #4363

**Pull request closed without merging**
