### PR TITLE
Don't generate RSA keys <1024 bits

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Needs https://github.com/twisted/twisted/pull/12095

**Comment by reaperhulk** [comment]
We should probably document this change

**Review by reaperhulk — APPROVED** [review]

**Comment by terryjreedy** [comment]
Thank you.  https://arstechnica.com/security/2024/08/home-energy-system-gives-researcher-control-of-virtual-power-plant/ is an example of why libraries should not allow easily cracked (for $70) keys.  Naive users will assume that they are OK.  (I am partly responding to https://github.com/pyca/cryptography/commit/83dcbc190165ad5c1f86bddaee76e0b288803c43#commitcomment-144797986 from @craigjbass.)  The referenced article links to this commit.

**Comment by craigjbass** [comment]
Yeah I understand the wider implications of pushing for secure key lengths but some way to override (opt in and partly hidden) would be welcomed by advanced users.

**Comment by chaen** [comment]
We run into the same problem and would be very happy to have a way of keeping the key length at 512

**Comment by reaperhulk** [comment]
It is increasingly likely that OpenSSL and other libraries are going to disable generation of 512-bit keys in the relatively near future. We still allow the parsing of this key length (although that may also be disabled by underlying libraries like boringssl soon!), but generally we'd strongly recommend moving to larger key sizes even in tests.

**Pull request merged**
