### PR TITLE
version bump for 37 release

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Blocked on a GH API bug, disabling auto-merge just so we don't accidentally approve and merge this.

**Comment by Tarnum-tst** [comment]
Sorry but what 37 release are You talking about?
There are at least 3 openned issues in 37 release milestone:
https://github.com/pyca/cryptography/issues/7035
https://github.com/pyca/cryptography/issues/7043
https://github.com/pyca/cryptography/issues/7065
Shouldn't these be fixed before release?

**Comment by reaperhulk** [comment]
We've chosen not to block 37 on the remaining issues, which will be pushed into later milestones as part of the release process. However, we aren't releasing 37 until the GH API issues are resolved.

**Comment by reaperhulk** [comment]
3.0.3 is coming April 26 so we're going to hold the 37.0 release for that. Going for the record for longest open release PR on this repo 😂

**Pull request merged**
