### PR TITLE
Add support for serialization.Encoding.TXT

### PR DESCRIPTION
**Pull request by tuxlife**
text output is beautiful for Debug and Verbose output.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Thanks for the contribution! However, I don't think I agree that output like this should be a serialization type. Additionally, if we were to implement this we'd need to build the strings ourselves since cryptography (while tied to OpenSSL at the moment) is not designed to require backend specific output like OpenSSL's `_print` functions.

What's your specific use case for this? Maybe there's another approach we can take.

**Comment by tuxlife** [comment]
for me, is a solution without `_print` okay.

It is very helpful, if you can 'check' your new Request with a human readable output like the Openssl-Output like this:
```
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: C=DE, L=Musterstadt, O=Foo Bar GmbH
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:ab:1f:f4:3a:30:0c:a9:a4:dc:13:d9:a3:d3:46:
                    5f:35:e8:ed:7e:20:5d:c6:45:8c:dd:de:d4:59:4b:
...
                    c1:c6:79:1f:01:0b:56:25:b0:e2:80:c3:13:fc:fa:
                    8e:ad
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: sha256WithRSAEncryption
         3f:dc:87:d1:25:b9:e5:eb:47:d7:54:20:a4:91:b2:f8:09:60:
...
         4e:88:09:5b:25:79:af:3f:5b:9e:20:a7:90:10:6f:5f:0d:4d:
         3f:3f:f6:bd
-----BEGIN CERTIFICATE REQUEST-----
MIICfzCCAWcCAQAwOjELMAkGA1UEBhMCREUxFDASBgNVBAcMC011c3RlcnN0YWR0
...
WyV5rz9bniCnkBBvXw1NPz/2vQ==
-----END CERTIFICATE REQUEST-----
```

**Comment by reaperhulk** [comment]
Right now it's possible to do this sort of printing by iterating the attributes on the `Certificate` object and just printing their `__repr__`. Maybe a Certificate's `__repr__` should be more than just the subject? We could make it show basically everything an openssl -text call shows quite easily.

**Comment by tuxlife** [comment]
@reaperhulk did you have a example for me?

**Comment by reaperhulk** [comment]
@tuxlife: Right now if you wanted to get the info that's present in a `-text` you'd basically need to do something like

```python
print(cert.issuer)
print(cert.subject)
print(cert.version)
print(cert.serial)
print(cert.not_valid_before)
print(cert.not_valid_after)
print(cert.extensions)
```
Which would give you pretty much the same set of info. We could (potentially) expand cert's `__repr__` to show most of that info. I'm not sure if I really want that or not, as printing the information is pretty simple already though.

**Comment by alex** [comment]
I think adding it to `__repr__` woudl be way to verbose for most CLI usage.

On Mon, Oct 12, 2015 at 9:13 AM, Paul Kehrer <notifications@github.com>
wrote:

> @tuxlife <https://github.com/tuxlife>: Right now if you wanted to get the
> info that's present in a -text you'd basically need to do something like
>
> print(cert.issuer)print(cert.subject)print(cert.version)print(cert.serial)print(cert.not_valid_before)print(cert.not_valid_after)print(cert.extensions)
>
> Which would give you pretty much the same set of info. We could
> (potentially) expand cert's __repr__ to show most of that info. I'm not
> sure if I really want that or not, as printing the information is pretty
> simple already though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/2331#issuecomment-147449028>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by tuxlife** [comment]
And how works it with Requests?

```python
bio = csr._backend._create_mem_bio()
csr._backend._lib.X509_REQ_print_ex(bio, csr._x509_req, 0, 0)
print(csr._backend._read_mem_bio(bio).decode())
print(csr.public_bytes(serialization.Encoding.PEM).decode())
```

    Certificate Request:
        Data:
            Version: 0 (0x0)
            Subject: O=Example Inc., OU=IT, L=Musterstadt/postalCode=12345/street=Example Strasse 1, ST=Musterstate, C=DE/emailAddress=info@example.com, CN=test.example.org
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2050 bit)
                    Modulus:
                        02:6f:65:38:85:ff:0e:fe:39:f0:8b:83:46:ff:23:
                        6e:9d
                    Exponent: 65537 (0x10001)
            Attributes:
            Requested Extensions:
                X509v3 Subject Alternative Name: 
                    DNS:test.example.org, DNS:test.example.com
        Signature Algorithm: sha256WithRSAEncryption
             00:28:49:09:98:60:55:b8:a4:78:c0:97:d7:27:91:59:da:96:
             d1:81:46:b0:b9
    -----BEGIN CERTIFICATE REQUEST-----
    MIIDTDCCAjMCAQAwgcUxFTATBgNVBAoMDEV4YW1wbGUgSW5jLjELMAkGA1UECwwC
    SVQxFDASBgNVBAcMC011c3RlcnN0YWR0MQ4wDAYDVQQRDAUxMjM0NTEaMBgGA1UE
    CQwRRXhhbXBsZSBTdHJhc3NlIDExFDASBgNVBAgMC011c3RlcnN0YXRlMQswCQYD
    VQQGEwJERTEfMB0GCSqGSIb3DQEJARYQaW5mb0BleGFtcGxlLmNvbTEZMBcGA1UE
    AwwQdGVzdC5leGFtcGxlLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBAm9lOIX/Dv458IuDRv8jkE5yEdRKMQkyFqIG+ZTQcy4YuZG0Ddx3prrttcov
    CsUcs49mE9NfEnFD71Uohxzb4dTwrd/kLmLh84Nkz+TKQkDOEsMlncTcTaxNF9xp
    3dAaRepGOC5rkb1rUEnFjiRwf+Dy89x8MYTMGkOvyeM9X1DRzpqzQ8w+1LqBioIx
    YfG4PVaWFkEr0YwQWTxwmdYBWk3QjgIHAo88TWFvzgeN7b2qF4yBvrxY2ujKIklh
    XkdVctpUkYPzpX2vsbajbIQXrH5ObIRQJN+gBwUbJgp65ZgqG6/sAxuPYbfCmrOM
    ZLNoGKCoSfbJ8jzs3ViY/vKXbp0CAwEAAaBAMD4GCSqGSIb3DQEJDjExMC8wLQYD
    VR0RBCYwJIIQdGVzdC5leGFtcGxlLm9yZ4IQdGVzdC5leGFtcGxlLmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQIAAChJCZhgVbikeMCX1yeRWdqWQ3ltarnlgUXoHnOKJXu2
    uBrI/rI8iCEsklgsjOXZn6/nbD51/dPjZ0L88a/zmGtA13Gatj+Wt21Z7Wv3dP2p
    8qaGF6Fgzs7Lh9aiZe/38gdfsqJvXta8wijSVmB1ZwTzksDhjMtJwPtewiYvpP1E
    2JV8Bez6cHO+PGNhHZjsYZEDbruUnw7AE7m0zFFUpww1u2Fh4kToPxmAxzOY8wuh
    J7vSUPjKB6+GwSA8jfjW1TsQGU6QI0Vmy3ZMJW9Q2Y2ncdTj2E8Leluyd1KUrWw6
    aKLiW1CiiaPmYkC4M84QiosQBN1opsc3Q0c70YFGsLk=
    -----END CERTIFICATE REQUEST-----
    



```python
type(csr.subject)
```

    cryptography.x509.name.Name


```python
csr.subject
```

    <Name([<NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.10, name=organizationName)>, value='Example Inc.')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.11, name=organizationalUnitName)>, value='IT')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.7, name=localityName)>, value='Musterstadt')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.17, name=Unknown OID)>, value='12345')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.9, name=Unknown OID)>, value='Example Strasse 1')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.8, name=stateOrProvinceName)>, value='Musterstate')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.6, name=countryName)>, value='DE')>, <NameAttribute(oid=<ObjectIdentifier(oid=1.2.840.113549.1.9.1, name=emailAddress)>, value='info@example.com')>, <NameAttribute(oid=<ObjectIdentifier(oid=2.5.4.3, name=commonName)>, value='test.example.org')>])>



```python
csr.subject.get_attributes_for_oid('localityName')
```

    []


```python
print(csr.extensions)
```

    <cryptography.x509.extensions.Extensions object at 0x7f27dc1ba898>

**Comment by reaperhulk** [comment]
Looks like we should add a `__repr__` that shows the containing extensions, but right now you can do `for i in csr.extensions: print(extension)`. Additionally, `get_attributes_for_oid` doesn't take a string (see: https://cryptography.io/en/latest/x509/reference/?highlight=get_attributes_for_oid#cryptography.x509.Name.get_attributes_for_oid).

**Comment by tuxlife** [comment]
I think, this is very difficult for a simple debug output

**Comment by reaperhulk** [comment]
We've added a __repr__ to extensions now. I'm open to potentially adding a helper function to print debug information (e.g. `x509_certificate_print(cert)`), but I'm against it being listed as a serialization type. If you'd like to open a new PR with a function based approach we can move forward there!

**Pull request closed without merging**
