### PR TITLE
Use flit instead of setuptools for vectors

### PR DESCRIPTION
**Pull request by alex**
Its much faster

### CODE REVIEW

**Comment by reaperhulk** [comment]
Do we need to modify the build requirements pins for this for when we build and publish?

**Comment by alex** [comment]
Hmm, it seems like we _should_ need to, but nothing is failing?

**Comment by alex** [comment]
Yeah, looks like it's not required.

**Comment by alex** [comment]
`build-requirements.txt` isn't used when we build the sdists, and that's the only place we do anything with vectors.

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
