### PR TITLE
Bump RSA-512 test keys to RSA-2048

### PR DESCRIPTION
**Pull request by davidben**
RSA-512 was broken in 1999. cryptography.io should not be requesting its backend library support it in 2024.

### CODE REVIEW

**Comment by alex** [comment]
`test-vectors.rst` needs to be updated, these are referenced at 

```
* OpenSSL PEM RSA serialization vectors from the `OpenSSL example key`_ and
  `GnuTLS key parsing tests`_.
```

**Comment by alex** [comment]
The docs for those should be moved down to the custom section now

**Comment by davidben** [comment]
Ah, didn't see the custom section. One moment...

**Comment by davidben** [comment]
Done.

**Review by alex — APPROVED** [review]

**Pull request merged**
