### PR TITLE
Don't allow update_into to mutate immutable objects

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Review by reaperhulk — APPROVED** [review]

**Comment by alittlesir** [comment]
Does this involve interface changes?

**Comment by reaperhulk** [comment]
It behaves exactly the same unless you were passing an immutable type (e.g. a byte string). So the interface has technically changed but in practice it has only changed for the vulnerable path.

**Comment by alittlesir** [comment]
In this case, change the buf class type from `bytes` to `bytearray`. it is OK?

it can't use the `bytes` type anymore.

```python
def update_into(self, data: bytes, buf: bytes) -> int:
```

**Comment by alittlesir** [comment]
I'm not sure what the effect of this vulnerability is.

**Comment by reaperhulk** [comment]
Unfortunately the Python type hint system doesn’t have a way to represent “all objects that implement the buffer protocol but only the mutable types”, so `bytes` is still the closest to “correct” type that we can declare.

**Comment by alittlesir** [comment]
What is the impact of this cve? I don't seem to feel the threat of this vulnerability.

**Pull request merged**
