### PR TITLE
add brainpool p256r1, p384r1, and p512r1 test vectors from OpenSSL

### PR DESCRIPTION
**Pull request by reaperhulk**
refs #4129 

This is a reformatting of data from https://github.com/openssl/openssl/blob/346149c164605cf0e1b930d3f42a1f28f3babcae/test/recipes/30-test_evp_data/evppkey.txt#L4981

### CODE REVIEW

**Comment by alex** [comment]
Does adding vectors from OpenSSL which we will then use as tests against OpenSSL make any sense?

**Comment by reaperhulk** [comment]
Running the test vectors ourselves does confirm that our code properly calls the underlying functions. I guess it might guard against regression in OpenSSL if they update something and improperly change the vectors, but that's not really a very realistic case. I mostly want these to confirm that we haven't mis-wired anything when doing ECDH with unusual curves.

**Comment by alex** [comment]
Ok. Are there no 3rd party vectors we can use?

**Comment by reaperhulk** [comment]
https://tools.ietf.org/html/rfc7027#appendix-A may be a good alternative. Could probably reformat those into the NIST ECDH vector format pretty easily.

**Pull request closed without merging**
