### PR TITLE
expand withnumbers refs #1286

### PR DESCRIPTION
**Pull request by reaperhulk**
- [x] Do this for elliptic curve
- [x] Add changelog entry

This is a PR to jump start the discussion of #1286. Fixing method/property consistency may be tricky (is there a way to have a method/property with the same name on a class?).

### CODE REVIEW

**Comment by reaperhulk** [comment]
Interested in opinions on methods vs properties (and how we might deprecate to be consistent). cc @public @alex @ronf

**Comment by alex** [comment]
The reason they are "incosistent" right now is a conceptual difference: Key
-> Numbers potentially involves computation, so it's a method,
PrivateNumbers -> PublicNumbers is just returning the subset of data, so
it's a property.

On Mon, Feb 16, 2015 at 12:22 PM, Paul Kehrer <notifications@github.com>
wrote:

> Interested in opinions on methods vs properties (and how we might
> deprecate to be consistent). cc @public <https://github.com/public> @alex
> <https://github.com/alex> @ronf <https://github.com/ronf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1662#issuecomment-74543065>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
Okay, so we can leave the method/property distinction in place. Is there an objection to adding these convenience methods?

**Comment by alex** [comment]
Not sure how I feel about them. I guess it's a fairly explicit transition
from private -> public.

On Tue, Feb 17, 2015 at 12:10 PM, Paul Kehrer <notifications@github.com>
wrote:

> Okay, so we can leave the method/property distinction in place. Is there
> an objection to adding these convenience methods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1662#issuecomment-74706215>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by public** [comment]
I quite like that `key.public_key().public_numbers()` makes it quite obvious that `key` is a private key currently.

If private keys were interoperable as public keys it would be easier to send private data to a function that was only ever really intended with public data in mind. I'm not sure how much of a footgun this is in practice though.

**Comment by alex** [comment]
That strict distinction was definitely my motivation when I originally
worked on this stuff.

On Mon, Feb 23, 2015 at 9:23 AM, Alex Stapleton <notifications@github.com>
wrote:

> I quite like that key.public_key().public_numbers() makes it quite
> obvious that key is a private key currently.
>
> If private keys were interoperable as public keys it would be easier to
> send private data to a function that was only ever really intended with
> public data in mind. I'm not sure how much of a footgun this is in practice
> though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1662#issuecomment-75588421>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
I am neutral about this so if we want to say "no we don't want these convenience methods because they hide some of the subtlety" that's fine. These ideas touch #1286, #1288, and probably #1339 so we can probably close all 3 if we are happy with the current layout.

**Comment by alex** [comment]
This either needs a rebase or be closed.

**Comment by reaperhulk** [comment]
Okay, consensus for now is that this is working as designed. We want the verbosity to make it clear to the user what exactly is going on (obtaining public numbers from a private key for example).

**Pull request closed without merging**
