### PR TITLE
Switch to codecov.io from coveralls

### PR DESCRIPTION
**Pull request by reaperhulk**
(Testing codecov again)

### CODE REVIEW

**Comment by alex** [comment]
FWIW tests are failing here because of a flake8 thing fixed in #1664, maybe try rebasing and see if this works with passing tests?

**Comment by reaperhulk** [comment]
I'll try. Currently looks like badging uses the last build submitted (rather than combined) and branch data still looks wrong.

**Comment by reaperhulk** [comment]
https://codecov.io/github/pyca/cryptography/src/cryptography/hazmat/backends/openssl/rsa.py?ref=master#73

Still not doing what we need :(

Badge is also inaccurate (https://codecov.io/github/pyca/cryptography/coverage.svg?branch=master) as it appears to just use whatever the last submitted build is rather than the combined coverage.

**Comment by reaperhulk** [comment]
Closing this because codecov has some serious bugs with merged coverage and they don't appear to be going away (wrong partial coverage info, claimed misses in merged coverage that individual builds say have 100%, and badging that is based on the last build rather than total merged coverage).

**Comment by alex** [comment]
Sounds good, we can review at some hypothetical later date when we hear
something good, until then not enough hours in a day for this.

On Sun, Mar 1, 2015 at 8:45 PM, Paul Kehrer <notifications@github.com>
wrote:

> Closed #1471 <https://github.com/pyca/cryptography/pull/1471>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/pull/1471#event-244124707>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
reopening because we haven't tried this in awhile

**Comment by reaperhulk** [comment]
oh, guess we can't

**Pull request closed without merging**
