### PR TITLE
Attempt to use coverage to quantify how many of the CONDITIONAL_NAMES we really use

### PR DESCRIPTION
**Pull request by alex**
(again)

### CODE REVIEW

**Comment by alex** [comment]
@reaperhulk ok, it looks like our remaining untested branches are:

- `Cryptography_HAS_CMAC`
- `Cryptography_HAS_EC`
- `Cryptography_HAS_ECDH`
- `Cryptography_HAS_ECDSA`
- `Cryptography_HAS_EC_CODES`
- `Cryptography_HAS_TLSv1_2`
- `Cryptography_HAS_RELEASE_BUFFERS`
- `Cryptography_HAS_SSL_OP_MSIE_SSLV2_RSA_PADDING`
- `Cryptography_HAS_NETBSD_D1_METH`
- `Cryptography_HAS_DTLS`

Should I just send a PR removing all these branches (probably two PRs), or are there any you want to argue in favor of keeping?

**Comment by reaperhulk** [comment]
I've confirmed release buffers, CMAC, and TLS1.2 should all be unnecessary at this point. I'm confused why we have SSL_OP_MSIE_SSLV2_RSA_PADDING. Presumably pyOpenSSL, but pyOpenSSL doesn't check for presence at all.

Pretty sure `NETBSD_D1_METH` is a workaround for a NetBSD specific issue so we need to keep that.

Not sure about the others yet, although I'm inclined to believe we should be safe assuming EC support at this point...

**Comment by alex** [comment]
Ok, now left remaining:

- `Cryptography_HAS_EC`
- `Cryptography_HAS_ECDH`
- `Cryptography_HAS_ECDSA`
- `Cryptography_HAS_EC_CODES`
- `Cryptography_HAS_NETBSD_D1_METH`
- `Cryptography_HAS_DTLS`

I guess I'll do one more PR to remove the EC stuff, and then we'll figure out what needs to happen with the DTLS stuff.

**Comment by alex** [comment]
So now we're down to `Cryptography_HAS_NETBSD_D1_METH` and `Cryptography_HAS_DTLS`. It sounds like we need NetBSD in our CI to hit the former. Do we still need the vanilla DTLS branch?

**Comment by alex** [comment]
Ok, we got the data and did the necessarry cleanups. Declaring victory!

**Pull request closed without merging**
